In [ ]:
import os 
from glob import glob
import pandas as pd

In [ ]:
# 특정 경로에서 파일의 목록을 가져오는 기능 
os.listdir("./review")

In [ ]:
# glob 라이브러리 사용
# 장점 : 파일의 경로와 파일 명이 동시에 출력 
#       특정 확장자만 목록을 불러올수 있다. 
json_list = glob("./review/*.json")

In [ ]:
# json_list를 이용하여 여러 파일들을 하나의 데이터프레임으로 결합 

# 비어있는 데이터프레임을 생성 
total_df = pd.DataFrame()

for file_path in json_list:
    # print(file_path)
    # break
    df = pd.read_json(file_path)
    # df를 total_df에 단순 행 결합 
    total_df = pd.concat( [total_df, df], axis = 0 )
total_df.reset_index(drop = True, inplace=True)
total_df.info()

In [ ]:
total_df.head(2)

In [ ]:
aspect_df = pd.DataFrame(sum(total_df['Aspects'], []))

In [ ]:
aspect_df.head()

In [ ]:
# 결측치가 존재하는가?
aspect_df.info()

In [ ]:
aspect_df = aspect_df.map(lambda x : x.strip())

In [ ]:
(aspect_df == '').sum()

In [ ]:
# 종속 변수들의 데이터의 빈도수를 확인 
aspect_df['Aspect'].value_counts()

In [ ]:
aspect_df['SentimentPolarity'].value_counts()

In [ ]:
# 독립 변수에서 중복된 데이터가 존재하면 제거 
aspect_df.drop_duplicates('SentimentText', inplace=True)

In [ ]:
aspect_df['SentimentPolarity'].value_counts()

In [ ]:
# 인덱스 초기화
aspect_df.reset_index(drop=True, inplace=True)

In [ ]:
# 독립 변수를 토큰화 -> 벡터화 
from konlpy.tag import Okt
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
# 토큰화 과정에서 특정 품사들만 사용
# 명사, 동사, 형용사, 부사

okt = Okt()
allow_pos = ['Noun', 'Verb', 'Adjective', 'Adverb']

def tokenize(text):
    result = []
    for word, pos in okt.pos(text):
        if (pos in allow_pos) & (len(word) >= 2):
            result.append(word)
    return result

tokenize(
    aspect_df.loc[0, 'SentimentText']
)

In [112]:
vec = TfidfVectorizer(
    tokenizer= tokenize, 
    ngram_range= (1, 2), 
    min_df= 3, 
    max_df = 0.8, 
    max_features= 3000
)

In [ ]:
aspect_df.columns

In [ ]:
X = aspect_df['SentimentText'].values
y1 = aspect_df['Aspect'].values
y2 = aspect_df['SentimentPolarity'].values

In [ ]:
X_vec = vec.fit_transform(X)

In [ ]:
X_vec.shape

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le1 = LabelEncoder()
y1_le = le1.fit_transform(y1) 
le2 = LabelEncoder()
y2_le = le2.fit_transform(y2)

In [ ]:
from sklearn.svm import LinearSVC

In [ ]:
svc1 = LinearSVC(class_weight='balanced', random_state=42)
svc2 = LinearSVC(class_weight='balanced', random_state=42)

In [62]:
svc1.fit(X_vec, y1_le)
svc2.fit(X_vec, y2_le)

LinearSVC(class_weight='balanced', random_state=42)

In [ ]:
X_vec[-500:]

In [ ]:
y1_le[-500:]

In [ ]:
pred_1 = svc1.predict(X_vec[-500:])
pred_2 = svc2.predict(X_vec[-500:])

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(pred_1, y1_le[-500:]))

In [ ]:
print(classification_report(pred_2, y2_le[-500:]))

- Ascept 컬럼과 SentimentPolarity 컬럼의 데이터를 결합 
- LabelEncoder를 이용하여 수치로 변환 
- Kfold, Pipe, GridsearchCV를 활용
- 계층화 폴드화는 5개 
- 벡터화, 모델 학습을 파이프라인으로 생성 
- 파라미터 조합은 벡터화에서 max_features의 조합은 (3000, None)
- SVC 모델의 조합은 C 값을 (1.0, 2.0)
- 최적의 모델의 스코어를 확인

In [ ]:
aspect_df.info()

In [ ]:
aspect_df['Aspect'] + '_' +aspect_df['SentimentPolarity']

In [42]:
from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.pipeline import Pipeline

In [43]:
X = aspect_df['SentimentText'].values
y = (aspect_df['Aspect'] + '_' + aspect_df['SentimentPolarity']).values

In [44]:
le = LabelEncoder()
y_le = le.fit_transform(y)

In [45]:
y_le

array([17, 12,  5, ..., 17, 17, 19], shape=(10467,))

In [46]:
pipe = Pipeline(
    [
        ('vector', vec), 
        ('model', svc1)
    ]
)
cv = StratifiedKFold(
    n_splits=5, shuffle=True, random_state=42
)
params = {
    'vector__max_features' : [3000, None], 
    'model__C' : [1.0, 2.0]
}

In [47]:
grid = GridSearchCV(
    estimator= pipe, 
    param_grid= params, 
    cv = cv
)

In [48]:
grid.fit(X, y_le)

c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_split.py:813: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('vector',
                                        TfidfVectorizer(max_df=0.8,
                                                        max_features=3000,
                                                        min_df=3,
                                                        ngram_range=(1, 2),
                                                        tokenizer=<function tokenize at 0x000001E6897C57A0>)),
                                       ('model',
                                        LinearSVC(class_weight='balanced',
                                                  random_state=42))]),
             param_grid={'model__C': [1.0, 2.0],
                         'vector__max_features': [3000, None]})

In [49]:
grid.best_score_

np.float64(0.7412812800753501)

In [50]:
# 종속 변수를 2차원의 데이터로 그대로 활용 
X = aspect_df['SentimentText'].values
le = LabelEncoder()
aspect_df['Aspect_le'] = le.fit_transform(aspect_df['Aspect'])
aspect_df['SentimentPolarity'] = aspect_df['SentimentPolarity'].astype(int)
y = aspect_df[ ['Aspect_le', 'SentimentPolarity'] ].values

In [52]:
y.shape

(10467, 2)

In [53]:
X.shape

(10467,)

In [117]:
vec = TfidfVectorizer(
    tokenizer=tokenize, 
    ngram_range= (1,2), 
    min_df = 3, 
    max_df = 0.8, 
    lowercase= False
)

In [118]:
X_vec = vec.fit_transform(X)

c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [ ]:
svc = LinearSVC(random_state=42, class_weight='balanced')

In [59]:
from sklearn.multioutput import MultiOutputClassifier

In [60]:
# MultiOutputClassifier는 분류모델에서 종속변수가 2차원 이상인 경우 사용하는 객체 
multi_model = MultiOutputClassifier(svc)

In [74]:
multi_model.fit(X_vec, y)

MultiOutputClassifier(estimator=LinearSVC(random_state=42))

In [73]:
print(type(y[0][0]), type(y[0][1]))

<class 'numpy.int64'> <class 'numpy.int64'>

In [89]:
from sklearn.model_selection import KFold
cv2 = KFold(n_splits=5, random_state=42, shuffle=True)

In [92]:
# 쉬는시간에 확인 

pipe = Pipeline(
    [
        ('vector', vec),
        ('model', multi_model)
    ]
)
params = {
    'model__estimator__C' : [0.8, 1.0]
}
grid = GridSearchCV(
    estimator= pipe, 
    cv = cv2, 
    param_grid= params, 
    scoring= 'accuracy'
)

In [ ]:
grid.fit(X, y)

In [80]:
pred = multi_model.predict(X_vec[-20:])

In [ ]:
pred

In [83]:
pred_df = pd.DataFrame(
    pred, columns = ['aspect', 'polarity']
)
pred_df['text'] = X[-20:]

In [85]:
pred_df['aspect'] = le.inverse_transform(pred_df['aspect'])

In [86]:
pred_df

   aspect  polarity                                  text
0     디자인         1                       디자인이 너무너무 예쁩니다.
1      색상         1                   색상도 고급스러워서 마음에 들구요.
2      마감         1                   바느질도 꼼꼼하게 잘 되어 있어요.
3      촉감         1                       털 감촉도 아주 부드러워요~
4       핏         1                  입어 보면 핏이 더 예쁜 자켓이예요~
5      가격         1                   가격 대비 가성비 좋은 제품이예요~
6      색상         1                              색상도 좋구요~
7     사이즈         1                  모자 크기도 적당해서 마음에 들어요.
8     디자인         1            모자가 있다 보니 밍크 특유의 올드함이 없네요.
9     디자인         1                          디자인 마음에 들어요.
10     마감        -1                      이음새가 좀 넓은 곳이 있지만
11     기능         1  얇은 목 폴라 입고 입으면 따뜻하고 포근한 느낌에 기분이 좋아요.
12     무게         1                      이 옷은 무게가 참 가벼워요.
13     두께         1                  봄가을에 입기가 딱 좋은 두께입니다.
14    디자인         1      디자인도 플리츠가 전체적으로 앞,뒤로 들어가서 멋스러워요.
15    착용감         1                     훌렁훌렁 편하게 입기가 좋아요.
16    사이즈         1                 입어보니 후드가 작지 않아서 좋았어요.
17    디자인         1                플리츠라서 고급스러우면서도 어려보이네요.
18    디자인         1          밑으로 내려갈수록 넓어지는 디자인이 마음에 들어요.
19     마감         1                       바느질도 잘 되어 있답니다~

In [94]:
# 긴 문단을 문장 별로 나눠주기 위해 Kkma로드 
from konlpy.tag import Kkma

In [95]:
kkma = Kkma()

In [97]:
file_list = glob("./test/*.json")
file_list

['./test\\1-1.여성의류(1).json',
 './test\\1-1.여성의류(2).json',
 './test\\1-1.여성의류(3).json']

In [98]:
test_df = pd.DataFrame()

for file in file_list:
    df = pd.read_json(file)
    test_df = pd.concat( [test_df, df], axis=0 )

test_df.reset_index(drop=True, inplace=True)
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Index            300 non-null    int64
 1   RawText          300 non-null    object
 2   Source           300 non-null    object
 3   Domain           300 non-null    object
 4   MainCategory     300 non-null    object
 5   ProductName      300 non-null    object
 6   ReviewScore      300 non-null    int64
 7   Syllable         300 non-null    int64
 8   Word             300 non-null    int64
 9   RDate            300 non-null    int64
 10  GeneralPolarity  298 non-null    float64
 11  Aspects          300 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 28.3+ KB

In [108]:
sample_text = test_df.loc[12, 'RawText']
sample_text

'털이 엄청나게 빠집니다 면 바바리에 엄청나게 묻어나고  하루입고벗었더니 겨드랑이같은곳도 엄청 뭉처있니에요 그래서 세탁을 했더니 끝도없이 손에 털뭉치???? 들이 묻어나서 포기했습니다 이게불량인가요 왜이렇게 만드신건가요 옷디자인은 너무맘에드는데 털빠짐때매 옷이아니네여'

In [109]:
# sample_text를 문장별로 나눠준다. 
text_list = kkma.sentences(sample_text)
text_list

['털이 엄청나게 빠집니다',
 '면 바바리에 엄청나게 묻어나고 하루 입고 벗었더니 겨드랑이 같은 곳도 엄청 뭉처있니에요 그래서 세탁을 했더니 끝도 없이 손에 털 뭉치???? 들이 묻어나서 포기했습니다',
 '이게 불량인가요',
 '왜 이렇게 만드신 건가요',
 '옷 디자인은 너무 맘에 드는데 털 빠짐 때 매 옷이 아니 네 여']

In [ ]:
# text_list를 벡터화  -> 모델을 이용하여 예측

In [121]:
pred = grid.predict(text_list)

In [122]:
pred

array([[ 1,  1],
       [15,  1],
       [15, -1],
       [ 2,  1],
       [ 5,  1]])

In [123]:
pred_df = pd.DataFrame(pred, columns = ['aspect', 'polarity'])
pred_df['text'] = text_list

pred_df

   aspect  polarity                                               text
0       1         1                                       털이 엄청나게 빠집니다
1      15         1  면 바바리에 엄청나게 묻어나고 하루 입고 벗었더니 겨드랑이 같은 곳도 엄청 뭉처있니...
2      15        -1                                           이게 불량인가요
3       2         1                                      왜 이렇게 만드신 건가요
4       5         1                옷 디자인은 너무 맘에 드는데 털 빠짐 때 매 옷이 아니 네 여

In [124]:
pred_df['aspect'] = le.inverse_transform(pred_df['aspect'])
pred_df

  aspect  polarity                                               text
0     기능         1                                       털이 엄청나게 빠집니다
1     품질         1  면 바바리에 엄청나게 묻어나고 하루 입고 벗었더니 겨드랑이 같은 곳도 엄청 뭉처있니...
2     품질        -1                                           이게 불량인가요
3     길이         1                                      왜 이렇게 만드신 건가요
4    디자인         1                옷 디자인은 너무 맘에 드는데 털 빠짐 때 매 옷이 아니 네 여

In [125]:
pred_df['RawText'] = sample_text
pred_df

,aspect,polarity,text,RawText
0,기능,1,털이 엄청나게 빠집니다,털이 엄청나게 빠집니다 면 바바리에 엄청나게 묻어나고 하루입고벗었더니 겨드랑이같은...
1,품질,1,면 바바리에 엄청나게 묻어나고 하루 입고 벗었더니 겨드랑이 같은 곳도 엄청 뭉처있니...,털이 엄청나게 빠집니다 면 바바리에 엄청나게 묻어나고 하루입고벗었더니 겨드랑이같은...
2,품질,-1,이게 불량인가요,털이 엄청나게 빠집니다 면 바바리에 엄청나게 묻어나고 하루입고벗었더니 겨드랑이같은...
3,길이,1,왜 이렇게 만드신 건가요,털이 엄청나게 빠집니다 면 바바리에 엄청나게 묻어나고 하루입고벗었더니 겨드랑이같은...
4,디자인,1,옷 디자인은 너무 맘에 드는데 털 빠짐 때 매 옷이 아니 네 여,털이 엄청나게 빠집니다 면 바바리에 엄청나게 묻어나고 하루입고벗었더니 겨드랑이같은...

In [127]:
# test_df에서 RawText의 데이터들을 문장 별로 나눠준다. 
# raw_list 리뷰 문단을 문장으로 나눈 리스트를 담기 위한 공간 
raw_list = []
# raw_dict 리뷰 문단마다 index를 키 값으로 value는 리뷰 문단 
raw_dict = {}
for i in range(len(test_df)):
    raw_list.append(
        kkma.sentences(
            test_df.loc[i, 'RawText']
        )
    )
    raw_dict[i] = test_df.loc[i, 'RawText']

In [ ]:
# raw_list
sentence_df = pd.DataFrame()
for idx, raw in enumerate(raw_list):
    pred = grid.predict(raw)
    temp_df = pd.DataFrame(pred, columns = ['Pred_Aspect', 'Pred_Polarity'])

[['가격이 착하고 디자인이 예쁩니다'],
 ['싸고 디자인이 예뻐요. .', '정말 가 성비 가심 비 입니다'],
 ['편하고 디자인이 예뻐요', '가격도 좋아요', '시 원해요 빨리 마르고 이것만 입게 되요'],
 ['너무 착한 가격에 감사합니다', '윈하는 색은 없지만'],
 ['가격이 너무 좋아서 블랙 구매했습니다', '그런데 소재도 맘에 들어 흰색도 구매했습니다'],
 ['외출할 때 입기에는 재질도 디자인도 좀~ 그러네요', '그냥 집에서 편하게 입을 수는 있을 것 같아요'],
 ['특히 자켓이 넘 작고 짧으네요. 상의는 좀 작구 바지는 잘 맞아요.'],
 ['싸고 품질이 좋아요', 'ᆢ 사이즈는 좀 큰 듯하구요', 'ᆢ 반 사이즈는 내려서 주문 하심 좋을 듯해요'],
 ['바지가 너무 편하고 좋아요', '티셔츠는 여름에 잘 입을 듯 베스트는 디자인은 별로 지만 가격이 착해서 만족'],
 ['디자인이 예뻐요.', '사이즈 잘 맞습니다.'],
 ['사이즈 딱 맞구요.', '너무 예쁘고 얇지도 두껍지도 않으네요.'],
 ['저렴하게 구입해서 겨울에 잘 입을 거 같아요'],
 ['털이 엄청나게 빠집니다',
  '면 바바리에 엄청나게 묻어나고 하루 입고 벗었더니 겨드랑이 같은 곳도 엄청 뭉처있니에요 그래서 세탁을 했더니 끝도 없이 손에 털 뭉치???? 들이 묻어나서 포기했습니다',
  '이게 불량인가요',
  '왜 이렇게 만드신 건가요',
  '옷 디자인은 너무 맘에 드는데 털 빠짐 때 매 옷이 아니 네 여'],
 ['디자인이 여성스러운 분위기가 납 니다 구겨져 와서 다림질 필요했어요'],
 ['99 사이즈 입는데 88 사이즈 잘 맞고~ 기장이 살짝 짧은 듯 하지만 밝은 색도 있고~ 까실까실 하니 좋으네요~'],
 ['4 종 마음에 들어요', '색깔도 이쁘고 여름 니트 입니다'],
 ['색상이 예쁘고 구김이 없어요'],
 ['색상 디자인 예쁘고 맘에 들어요'],
 ['가 성비 갑입니다',
  '가로 패턴이라 더 커 보이면 어쩌나 싶었는데 칼라고 디자인이고 다 만족합니다',
  '가슴도 좀 있는 편이라 걱정했는데 핏이 괸찮아요 비치지 않아서 하나만 입고 다녀도 될 만 합니다'],
 ['오 좋아요',
  '이 가격에 득 템 했네요',
  '살이 쪄서 고민이었는데 어지간히 커버도 되고 가볍고 시원할 듯 해요 잘 입을께요',
  '바로 세탁하느라 시 착만 해서 사진은 스크린 샷 으로 대체 해요 사진하고 똑 같으니 걱정 마 세요 추천 합니다'],
 ['가격대비 최고 예요 가볍고 좋아요'],
 ['그레이 상의는 비침이 약간 있지만 가격대비 짱이에요.', '상의는 래이 온인데 마 재질 느낌입니다'],
 ['싸게 잘 샀어요~', '여름내 시원하게 잘 입었습니다.'],
 ['너~~ 무 얇고 후들후들. 이런 건 팔지 마세요.', '색상도 별로 네 요.'],
 ['구김이 심하고 상의는 66 사이즈 시켰는데 기존 규격보다 너무 커서 못 입고 있어요', 'ㅠ'],
 ['가볍고 촉감이 부드러워 잘 입고 있습니다'],
 ['편하고 간편하게 입을 수 있어서 좋아요', '네이비로 구매했는데 셔츠와 바지가 색이 조금 달라서 별 점 하나 뺐어요'],
 ['사이즈 딱 맞고 디자인도 이쁘고 ~! 최고!!~~ 강추합니다'],
 ['재질은 까칠하고 바지는 핏이 별로 임'],
 ['바지 약간 비침 있어요..',
  '구김 가는 레이온이고.. 그렇게 각 잡힌 옷이 아니라서 다림질해야 하고 축축 쳐지는 느낌.. 뭐 가격대비 입을 만은 해요'],
 ['소재, 디자인도 좋아요',
  '사이즈가 좀 큰 듯해서 핑크로 작은 사이즈를 구매할까 했는데 품절인 듯 해서 그레이로 재구매 했어요',
  '좋은 상품 저렴하게 구매해서 좋아요'],
 ['네이비 입어 보고 착한 가격에 좋은 품질에 재구매 합니다'],
 ['소재가 인견 100% 라',
  '촉감이 부드럽고 시원합니다',
  '디자인도 예쁘고 다 달라 좋습니다',
  '다만 레드와 블루는 목선이 좁아 입을 때 조금 불편합니다',
  '뒤집어 보니 주머니 한쪽 면이 오 버룩 처리가 안되어 완성도가 완벽하지는 않은 듯 하네요',
  '모두 주머니가 있어 활용도가 좋습니다',
  '타 사보다 가격이 비싸지만 쿠폰 적립금 사용하여 저렴하게 구입했습니다',
  '잘 입겠습니다 ~',
  '^^'],
 ['가 성비 최고~ ^^ 시원하고 디자인도 좋아요'],
 ['시원하고 디자인이 넘 예뻐요', '자꾸 입게 되요'],
 ['시원하고 길이도 적당해요.'],
 ['생각보다 원단이 좋네요', '부드럽고 색감도 좋아요', '편하네요'],
 ['디자인도 색상도 모두 마음에 듭니다~', '시원할 거 같아요'],
 ['이렇게 디자인 좋은 옷이 이렇게 싸 다니 오자마자 입었는데. 정말 기가 막히네요.',
  '내가 입고 찍어서 이 모양이지만 진짜 좋아요.',
  '강추'],
 ['박시하게 해볼려고 일부로 한 사쥬 크게 주문했어요.',
  '40 대이고 키 작고 땅 땅한 체형입니다.',
  '까만색 읏 외출복으로도 괜찮고 파란색 빨간색은 라운지 웨어로 입어야 할 듯 천은 좋은 편이에요.',
  '주머니도 있고요.',
  '가성 비로 치면 만족합니다.'],
 ['너무 싸서 기대 안했는데 디자인 넘 이뻐요~~'],
 ['너무 맘에 듭니다', '인견 옷은 처음 구매한 건데 저는 좋네요', '디자인도 두께 감도 크기도 너무 잘 맞아서 추천하고 싶어요'],
 ['가격도 저렴하고 이뻐서 언니한테 선물로 보냈는데 넘 얇아서 집에서 편하게 입는 다고하네요~'],
 ['소재가 가볍고 색상도 산뜻하니 아주 좋아요.'],
 ['매우 만족합니다~', '시원하고 몽에 붙지 않아 좋아요~~'],
 ['OOO 인견 원피스 구매 후 디자인이 예쁜 듯해 구매했는데 길이가 주황색 원피스는 많이 짧네요',
  '그래도 다양한 디자인 좋아요~',
  '♡'],
 ['핏은 제가 살이 쪄서 55 반은 되는 거 같은데 55 주문했더니 레드가 좀 더 여유있고 블루도 편 한편이 예요~ 한 사이즈 업해서 입으면 핏이 안 이쁠 거 같아요..',
  '레드 세탁했더니 마감 올 살짝 풀림 ㅜ 암 튼 원단이 너무 좋아서 별 5개 아깝지 않네요~',
  '^^'],
 ['그냥 집에서 나 입어야 할 듯 편하긴 한데 이쁨은 별루'],
 ['저렴하게 구매 잘했어요.', '하지만 한 옷 바느질상태가 좋지 않아 기분이 별로. 반품하기 귀찮아 손 좀 봐 입네요.'],
 ['데일리 티셔츠로 아주 편하게 잘 입고 있습니다', '원단이 피부에도 좋고 촉감이 좋습니다'],
 ['엄마가 디자인을 좋아해요', '얇지만 괜찮아요'],
 ['소재도 좋고 맘에 꼭 들어요', '입어 보니 시원하고 편안해요'],
 ['품질 좋고 가격 좋고 득 템 했네요'],
 ['배송은 괜찮은데 색이 생각보다 노란 끼? 누런 색이라 놀랬어요',
  'ㅜㅜ 입어 보니 괜찮은 듯 하긴 하지만 색상이 썩 맘에 들 진 않아요',
  'ㅜㅜ 색 고민 후 선택 하세요~'],
 ['제품 저렴하고 이뻐요', '소재도 좋앙ᆢ'],
 ['저렴한 가격에 득 템입니다.', 'M 사이즈는 100~105 중간쯤으로 잘 맞습니다.'],
 ['저렴한 가격에 행사할 때 더 싸게 구매해서 너무 맘에 들어요'],
 ['약간 이 염되서 왔는데 그냥 입으려고요 입어 보니 핏이 이쁘긴 하네영'],
 ['얇은 니트 티 싸이즈는 좋은데 몸에 닿았을 때 따가운 감이 있네요'],
 ['생각보다 얇고 촉감이 약간 깔깔해요'],
 ['얇아서 입기 좋아요.', '가격대비 대만족입니다.', '감촉도 좋고 디자인도 괜찮아요'],
 ['얇은데 입어 보니 꽤 포근해요.', '재질도 부들부들 한 게 감촉도 괘 안구 디자인도 심심하지 않게 포인트 있어서 좋네요.'],
 ['색감도 굿 가격도 굿입니다'],
 ['잘 입고 있어요.', '따뜻하고 착용감이 편합니다'],
 ['보들보들 넘 좋아요..', '이가격에 3벌이나.. 진짜 최고..'],
 ['금액이 저렴해도 기대를 했었는데 그 갑 어치밖에 안 되는군요', '그만큼만 입겠습니다'],
 ['추위 타는 딸아이가 따뜻하고 목이 답답하지 않다고', '잘 입고 있어요~~~', '^^'],
 ['부들부들 포근하고 가볍고 따뜻해요', '색상도 다 맘에 드네요'],
 ['너무 따뜻하고 색깔도 이쁘고 다 만족합니다', '감사합니다', '잘 입을께요'],
 ['부 클 니트 따뜻하고 촉감이 부드러워요', '보풀이 일어나지 않았으면 좋겠어요'],
 ['싸이즈 없어서 안 사려다',
  '큰 사이즈로 구매하라는 쇼 호스트님 말 믿고 샀는데 너무 크네요',
  '특히 갈색은 목이 너무 커서 이상해 보여요 보풀도 많이 나고'],
 ['길이 감 엉덩이 덮여 괜 춘. 젤 큰 싸이즈 여서 인지 팔 길이가 길고 통이 넓어 별 하나 뺌. 가격대비 마음에 듬.'],
 ['목부분 디자인이 어 저 쩡 사이즈 없어서 젤 큰 사이즈 주문 길이는 짧고 품은 겁 나 큰...'],
 ['셋 다정 말 좋아요.', '전한 단계 내려와서 주문했지만 늘어난 까 바 서. 잘 맞아요.', '부드럽고. 강추..'],
 ['라이브방송보고 샀네요',
  '66 없어 77 했는데 오버 핏으로 좋네요.',
  '드라이크리닝하라 하는데 그냥 울 샴푸해서 입었는데 괜찮네요'],
 ['가격이 착해서 구매하기도 했는데 소프 트라는 이름답게 부드럽고 편안하네요~',
  '색상도 차분하니 다 좋아하는 거라',
  '맘에 듭니다~'],
 ['옷이 많이 크네요.', '감촉이 많이 까 끌 거려요'],
 ['생객보다 신축성 덜해서 목이 끼어요'],
 ['잘 늘어나서 편하고 부드러움 드라이크리닝 해야 하는 것이 아쉬움'],
 ['부드럽고 넉넉한 핏 맘에 들며 무엇보다도 가 성비가 좋아요~~', '^^ 기대 이상입니다~~.'],
 ['잘 받았습니다', '넉넉하게 입 을려 고 크게 주문했어요', '따뜻합니다', '보풀은 잘 생기겠네요'],
 ['사이즈 없어서 ( 쇼 호스트 분 99 착용보고) 차라리 루즈하게 크게 입 을려 고 99. 구입. 큰 사이즈도 나쁘지 않아요~~',
  '가격 생각하면 만족 합니다~~',
  '검정이 젤 맘에 들어요~~'],
 ['배송도 빠르고 옷도 넘 따뜻하고 포근하네요', '가격도 착해서 넘 잘산 거 같아요', '사이즈도 넉넉하고 편안하고 좋아요'],
 ['디자인도 틀리고 여러 가지 색상으로 저렴하게 사서 잘 입고 있어요~~', '^^'],
 ['저렴하게 구매했지만 잘 입을 것 같아요', '모두 다른 디자인이라 더 좋으네요'],
 ['저렴하게 잘 구매했구 여. 조끼까지 올겨울은 요 아이 하나로 입어야 겠네요'],
 ['어디에 나 잘 어울리고 따뜻하고 부드러워요', '^^ 가격대비 완전 만족 입니다'],
 ['목둘레가 좀 좁아 조심히 다뤄야 합니다', '색상 맘에 들고 특히 밍크 부분이 맘에 들고 따뜻합니다'],
 ['넥라인을 밍크로 둘러 따뜻해 보이고 하나로도 갖춰 입은 듯 좋습니다',
  '뒷목 연결부분이 약합니다',
  '옷 걸이에서 빼다가 터져서 꿰매느라 힘들었습니다'],
 ['가 성비 좋아 요~ 편하게 걸치기 좋고 색감도 좋네요', '제 사이즈 강추!!'],
 ['아주 만족스럽네요.',
  '두께는 얇아요',
  '소재도 원하던 느낌이구요',
  '기계 세탁되서 너무 좋습니다.',
  '그리고 코튼이라 안 끌 거림 없습니다.',
  '굿 굿'],
 ['95가 매진이라서 한 사이 즈크 걱 주문했더니 크긴 큰데 크게 입어서 괜찬아요~~',
  '면이라서 촉감도 좋고 늘어지지 않을 것 같아요~~',
  '만족합니다.'],
 ['베이지 구매해서 편안하게 잘 입었고 블랙이 예뻐서 재구매 합니다'],
 ['가격이 맘에 들어 주문했더니 옷 디자인이 더 맘에 들어 좋네요.',
  '따듯하고 피부에 닿는 느낌도 부드러워요.',
  '아쉬운 건 치수가 약간 작은지 팔 길이 약간 작네요.',
  '한 치수 크게 주문하면 될 듯하네요.'],
 ['가격대비 품질은 좋아요~', '패 팅 주머니가 뚫려서 온 거 말고는 만족합니다.'],
 ['가격대비 훌륭합니다', '조끼만 다른 분 들 상품평처럼 좀 싼 티는 나지만 그래도 잘 입을 듯요 득 템 했네요'],
 ['가격대비 넘 넘 맘에 들어요', '특히 기모가 있어서. 외출복으로도 좋아요'],
 ['의류 안에 기모가 아닌 베로 아로 되어서 더욱 따뜻함 니다 저렴한 가격으로 구매해서 더욱 좋아 요타방송보다 훨씬 저렴함 니다 단지 색상이 품절된 것이 있어서 아쉬웠음 니다'],
 ['티와 바진 ㄷㄴ 따듯 하겠고 질도 좋은데 베스트는 생각보다는 도톰하고 자크 없이 똑딱이고 ㅜㅜ 가슴 둘레가 좀 작게 나와 잠그지 안고 입어야 겠어요',
  '낚시 갈 때 입으려구요 일상 생활 복으로 좋을 듯 싶어요'],
 ['작년에 그레이로 잘 입고 오트밀로 색상 바꿔 주문해 봤어요',
  '옷이 넘 편해서 자주 손 가입 었어요',
  '대신 니트 재질이라 보니 보풀 감은 어쩔 수업 머요 ㅠㅠ'],
 ['사이즈가 작아도 너무 작아요.77', '사이즈가 55 정도밖에 안되는 듯... 반 품 비가 너무 비싸 장롱행.'],
 ['색상도 다양하고 저렴해서 구매 했습니다.',
  '가을엔 실외 복으로 착용해 즐겨 입었고 겨울엔 실내에서 아주 편안하게 잘 입고 있습니다.'],
 ['소재가 좋아요',
  '입 기편하고요',
  '엄마 사 드리고 좋아서 저도 추가 주문했네요',
  '편해서 홈 웨어로 너무 좋네요~~',
  '* 추천해 드려요'],
 ['가격이 너무 저렴해서 기대를 안했는데 바느질처리도 잘되어 있고 디자인도 정말 맘에 들어요', '^^'],
 ['빠른 배송 감사 드려요.', '옷이 부드럽고 색상도 이뻐요.', '여유있는 핏 이에요..'],
 ['가 성비 갑입니다.',
  '디자인도 이쁘고 길이도 적당히 짧지 않아서 더 좋았어요.',
  '아들이 엄마의 쇼핑 노하우가 대단하다고',
  '난리에요 아주 만족하고 적극 추천합니다'],
 ['봄 ㆍ 가을 편하게 잘빕을수있겠네요 소제가 차가운 소제 라 쌀쌀한 날씨에 인어로'],
 ['네 개가 모두 디자인이 달라서, 혼자 입어도 좋고, 가족이나 친구들과 나눠 입어도 될 듯해요.',
  '회색이랑 핑크는 아랫단 쪽이 좀 많이 넓어요.',
  '저는 양옆을 좀 찝어서 동생 줬더니 아주 좋아라',
  '합니다.',
  '저렴한 가격에 아주 만족합니다.',
  '편하게 잘 입을 것 같아요'],
 ['컬러도 예쁘고 디자인도 예쁘고 품질도 좋아요'],
 ['가격도 좋고 상품평이 좋아서 구매했는데 생각했던 거보다 더 퀄리티가 좋아요.',
  '이월된 옷이라 저렴한 건지... 할인을 많이 해 주셔서 소비자로선 좋네요.',
  '사이즈랑 색상 모두 맘에 들어요.',
  '오랜만에 득 템 했네요.',
  '고민하시는 분들 망설이지 말고 주문 하세요~~'],
 ['편하게 입을 수 있으며, 사이즈는 66 입는데 55 선택했는데 작지 않아요.', '옷감이 부드러워요.'],
 ['너무 저렴해서 기대 안했는데 네 가지 컬러 다 괜찮아요.',
  '신축성, 길이 감 다 적당하고 이가격에 완 젼 득 템 했네요.',
  '너무 좋아요~~'],
 ['편하게 입을 수 있네요', '소재가 지금 간 절기 옷이 예요 가격대비 가 성비 좋습니다', '감사합니다'],
 ['구성품도 다르고 티셔츠 2개는 목부분 엉망으로 만들었네요~',
  '싸게 판다고 품질이 걍 엉망이네요~',
  '상품평 좋아서 구매했는데 품질이 영 엉망이네요'],
 ['까 끌거린다는 평이 있어서 각오하고 주문했는데 저는 민감하지 않은 편이라 감촉은 괜찮았어요.',
  '핏은 적당하고 색상구성이 마음에 들었어요.',
  '봄 가을 겨울 이너로 편하게 입을 수 있는 전천후 아이템이네요.'],
 ['옷마다 사이즈가 약간씩 틀린 거 같네요',
  '목이 타이트하게 들어가는 옷도 있고 촉감이 거스릴 정도는 아닌 거 같은데 오래 입음 어찌 될지 모르겠네요',
  '사이즈가 한가지라',
  '그냥 구매했는데 날씬하신 분들이 입은 괜찮을 꺼 같은데 전체적으로 꽉 껴서 반품 하려다',
  '일단 입어 보기로 했네요'],
 ['디자인은 만족하나 소재가 넘 거칠어 목이 가려워요'],
 ['살짝 껄끄럽네요', '부드러운 게 아니네요', '그걸 말고는 가격도 싸고 배송도 빠르고 감사해요'],
 ['감촉도 좋고 모양도 맘에 들어 따뜻하고 예쁜 핏으로 입을 수 있어 기분좋으네요~ ^^'],
 ['사이즈가 작아요',
  '옷마다 길이 차이도 있구요',
  '원단도 까 슬 거려서 맨살에는 어렵구요',
  '곰팡이 냄새 같은 게 나요 반품하고 싶어요'],
 ['디자인과 가격대가 넘 맘에 들어 샀는데 넘 까 슬 거려 입기 넘 불편하네요', 'ㅠㅠ'],
 ['제품을 2017년도에 만든 거네요~',
  '어차피 집에서 편하게 입으려고 구매한 것이니 크게 상관은 없어요',
  '그러나 까 슬 거려서 맨살에는 NO! 어쨌든 저렴하게 구매했어요'],
 ['두껍지 않고 목이 올라와 있어서 아우터 안에 입기 딱 좋습니다',
  'ㅡ 조금 춥다 싶으면 스카프로 멋을 내세요',
  '^^* 가성 비 좋습니다',
  '( 맨 살에 입기에 약간 까슬하지만 괜찮아요)'],
 ['맨살에는 가슬가슬 해요 ㅠ 디자인 사이즈는 넘 좋구요'],
 ['가격대비 너무 만족스러운 제품입니다.', '네 가지 제품이 특색이 달라 요즈음 골라 입는 재미가 좋습니다.'],
 ['싸서 구매했는데 절대 모델 핏 나지 않아요',
  '제품서 비린 냄새가 나는데 만든지 한참된 옷이네요',
  'ㅜ 편하게 입을 것 같지도 읺 고 반품도 어렵네요',
  'ㅜㅜ'],
 ['싸서 구매 했더니 너무 까 슬 거려서 입 기가 별로 예요 ㅜㅜ'],
 ['맨살엔 깔끄럽고 요즘 입 기엔 앞 목이 답답해요.', '소재 색상 디자인 특히 값이 싸서 구입했는데 추천은 못 마겠네요.'],
 ['한철 입을 거 생각하고 샀어요..',
  '품질이 생각보다 괜찮네요..',
  '제일 큰 사이즈 구매했는데 사이즈가 크게 나 오진 않았습니다..'],
 ['목둘레가 너무 작아서 입구 벗기가 완전 불편 해요.. 저렴한 가격이 여서 엄청난 컬 리 티를 원한 건 아니지만.. 입을 수가 없네요'],
 ['기계 세탁하니 보풀이 생기네요', '집에서 입는 걸루 그래도 저렴하니 잘 입을께요'],
 ['넉넉하게 나왔구요', '편하게 막 입을 수 있는 길이 감도 적당합니다'],
 ['빠른 배송 감사 드려요.', '촉감이 부드럽고 색상이 넘 이뻐요.', '핏은 여유있어 편하고 좋아요'],
 ['가 성비 최고!! 적당한 두께에 지금시기에 딱 맞는 옷 이에요 왠 만한 상의 1벌 가격에 4벌을 쟁이네요',
  '밝은 색은 엄마 입으라고 드리고 검정, 하늘색은 제가 입고! 구성이 1석 2조 너무 좋네요',
  '평소 입는 사이즈로 딱 좋아요',
  '^^'],
 ['가격 저렴', '히 넘 잘 사서 잘 입고 있어 여. 완전 편하고 데일리로 딱 ^^'],
 ['잘 구매했구요', '검정색 목부분이 벌어지지 않아서 못 입어요.', '다른 것은 탄력이 있는데 ....'],
 ['디자인이 다른 건 만족해요~',
  '진짜 상품평대로 검은색은 신축성이 없어 머리가 들어가질 않네요',
  'ㅎㅎ 그냥 버렸어요..',
  '그게 아쉬워요.'],
 ['생각보다 얇지 않고 지그 입어도 괜찮네요~', '가격도 저렴하고 배송도 빠르고 추천합니다~'],
 ['이가격에 정말 만족합니다',
  '소재도 좋아서 따뜻할 거 같아요',
  '소매가 길어서 접어 입어야겠어요 다른 색도 있으면 색깔 별로 사고 싶네요'],
 ['블랙과 레드 티셔츠에 목부분에 올이 풀려 있네요',
  '95 사이즈 입는데 100으로 시켰는데도 품이 넉넉하지 않아요',
  '소매는 좀 마니 길구요',
  '교환을 할까 반품을 할까 고민 중 입 ㄴ ㄱ다'],
 ['잘 입을 것 같군요', '3 종류 디자인이 달라서 이뻐요', '니트도 운동할 때 괜찬아요'],
 ['상품 만족합니다',
  '실측 싸이즈가 좀 애매해서 문의 드렸더니 평소 입는 싸이즈로 주문하라 고해서 주문했는데 잘 맞습니다.',
  '쫀쫀한 니트 재질이고 길이 감도 좋아요',
  '비싼 브랜드 한 장도 안되는 가격으로 무려 3장이나 얻었네요',
  '보풀이 나는 재질도 아닌 것 같은데... 디자인도 색상도 젊어서 굿 굿입니다!',
  '겨울 라운딩이 기대됩니다',
  '착용 샷도 한번 올려보겠습니다',
  '적극 추천합니다'],
 ['옷 핏이 너무 예뻐요',
  '골프 치는 분께 추천하고 싶네요',
  '가격도 저렴하고 재질도 좋아요',
  '홈쇼핑에서 이런 골프 핏은 첨인 거 같앙ᆢ ㄷ 잘 입을게요',
  '감사합니다'],
 ['주변에서 마니 구입했는지 연습장에 같은 옷이 또 있네요~',
  '^^ 품질은 양호. 정 사이즈. 스판성은 그리 좋진 않고 드라이라',
  '해야 하니 가 성비는 별루에요.'],
 ['빨간색 옷을 먼저 입고 스크린 한번 쳣죠ᆢ 옷은 약간 두텁고 좋은데ᆢ 팔은 길고 몸 쪽으로 쫌 짧은 듯합니다',
  'ᆢ 제가 살이 쪄서 그런가?',
  'ᆢ 싶어서 집에 있는 볼 빅 옷이랑 비교하니 ᆢ 길이가 약간 차이가 납니다',
  'ㅋㅋᆢ 좀 길면 좋는데ᆢ 제 체형 때문일까?',
  '일단 ᆢ 검정색이 품질이 최고 좋아 보이고 ᆢ 다른 옷들도 좋습니다'],
 ['일단 받아 보니 디자인은 조금 촌스러워요', '옷은 기대 이상으로 따뜻합니다', '편하고 막 입기 좋아요'],
 ['좋은 가격에 3 종이라 감사히 입으려 했으나 본의 아니게 볼 때마다 화가 나서 글 남깁니다',
  'ㆍ 빨간색 티는 소매 밑단이 터지고 실밥이 거의 누더기상태로 포장되어 왔더군요',
  'ㆍ 어이 없는 새 옷요 ㆍ 반품 포장하다가 그냥 포기했네요',
  'ㆍ 믿을 만한 00 쇼핑을 통해 알 만한 브랜드를 구매했는데 실망스럽습니다',
  'ㆍ'],
 ['색상도 예쁘고 좋아요,', '감촉이 매끄러운 게 좋고 짜임이 쫀쫀하니, 좋아요~'],
 ['사이즈가 각각 다르네요 .',
  '한 치수 크게 주 문하라고 했는데 레드는 맞는데 2가지는 크네요',
  'ㅠㅠ 반품을 해야 할지 레드는 색상이 예뻐요 .',
  '소매 길이는 좀 긴 편입니다'],
 ['촉감이 너무 좋네요', '가격대비 완벽한 상품이예요', '근데... 한 치수 크게 사야 좋을 듯해 보여요'],
 ['싸이즈 딱 조아요 핏도 컬러도 예쁩니다.', '팔이 좀 길어요.'],
 ['착용하니 사이즈, 핏 좋아요', '디자인 맘에 들어서 많이 입을 거 같애요'],
 ['부드러운 니트 느낌 입니', '다 사이즈는 조금 타이트하게 나온 것 같고 디자인이 이쁘네요'],
 ['그냥 가격이 저렴해서 샀는데 따뜻해 보이는데 소재는 별로 싼 티가 나네요..', '누구 주기도 그렇고..'],
 ['편하게 입기에 좋네요', '소제는 별로 지만 가격에 비해 괜찮은 것 같아요'],
 ['일단 저렴한 상품 가에 호기심으로 구매하였습니다.',
  '생각보다 착용감이 좋았고 보온성이 뛰어나고 옷 매무새도 마음에 들었습니다.',
  '강추입니다.'],
 ['재질이 별로 여요 그 치만 넉넉한 품 땜에 입기로 해ㅛ어요'],
 ['가 성비 갑입니다', '포장도 정성스럽네요', '그리고 따 끗한 데 소재는 쫌..'],
 ['두 번째 구매입니다.',
  '소재는 별로 지만 따뜻하고 체형 커버되는 디자인에 가 성비가 너무 좋아요.',
  '제 사이즈보다 한 치수 내려 입어도 여유있어요.'],
 ['커도 너무 크구요.', '소재도, 두껍지도, 부드럽지도, 글쎄 반품이 여의치 않아 그냥 두었습니다.'],
 ['겨울 내내 지금 까지도 잘 입고 있어요', '세 탁도 편하고 가격대비 색상도 다 야 애서 대체로 만족해요'],
 ['사이즈가 넘 크게 나와서 맘에 않 들어요',
  '66 입어서 구입했는데 88 같은 사이즈에 깜 놀 교환하고 싶은데 교환 비가 6천원 배보다 배꼽이 크네요',
  '저렴해서 구입했건만 속 상하 넹ᆢ ㄷ'],
 ['재질은 얇고 부드러워요',
  '세 탁기 돌려도 줄거나 변형 없구요',
  '몸통은 풍덩 해서 편하고 좋은데 팔뚝은 여유 없이 꽉 끼어서 입고 있으면 좀 답답하고 불편 해요.. 심지어 가오리 스탈이라.. 어깨선도 뭔 가 옷을 앞뒤 반대로 입은 것처럼 어 딘가 불편해요'],
 ['가볍고 따뜻해요', '다만 목부분이 많이 느슨해서 많이 추운 날에는 목도리를 꼭 해야겠네요'],
 ['반짝이 원단이 생각보다 많아요', '편하게 입기 좋고 사이즈 넉넉해요'],
 ['66을 햇는데도 목부분이 너무 쪼입니다.',
  '사진상은 여유로운 스탈 같아서 구매한 건데... 잡아 늘리고 있네요ㅋ저렴해서 패스입니다.'],
 ['두껍지 않으면서 부드럽고 따뜻한데 맨살에 입어도 아무렇지도 않아요.',
  '자켓 이너로 좋겠어요.',
  '이런 가격에 이정도 라니 완전 가 성비 갑입니다.'],
 ['색상 질감 다 맘에 듭니다', '신축성도 좋아 입고 벗기 편합니다'],
 ['두껍지 않아서 레이 어드 하기 좋아요.', '반짝이가 과하지 않고 은은함. 정 사이즈로 입으면 되고 길이는 힙을 덮을 정도는 아님'],
 ['가격대비 상품의 질이 너무 좋아요', '보들보들 해서 잘 하고 다닐 것 같아요'],
 ['흘러내리듯 매우 부드럽고 착용감이 좋고 따뜻하네요'],
 ['상품의 만족도 good! 소장의 가치도 goood! 따뜻하고 부드럽고 아무렇게 나 둘러도 멋스럽고 색상도 이쁩니다.'],
 ['레깅스에 입으려 한 치수 크게 샀는데 많이 길 진안아요 저렴', '히 잘 샀습니다.'],
 ['싼값에 반품은 안해요.. 팔 길이가 3 종 모두 달라요.', 'ㅜㅜ 줄차로 재 봤더니 3 센치나 차이나네요'],
 ['두껍지도 얇지도 적당한 기모 고급 지진 않지만 편하게 입을 수 있을 것 같아요.'],
 ['디자인도 예쁜 정말 나무랄 때 없는 좋은 상 품 이예요~',
  '살짝 아쉬움이 있다면 색상 밝은 컬러를 하나쯤 더 있었으면 좋았을 것 같아요~'],
 ['잘 받았습니다', '약품 냄새가 심하네요', '옷은 따뜻하고 착용감은 편합니다'],
 ['빠른 배송 감사하고 가격 저렴하게 잘 구입했어요',
  '^^ 품질도 좋고 사이즈도 넉넉하고 따뜻해요',
  '코트 안에 입으니 너무 좋으네요'],
 ['팔기장이 잘 안 맞아서 늘 좀 짧은 듯 입었는데 이상품은 팔기 장도 알맞게 길고 품도 적당하게 떨어져서 맘에 들어요',
  '싼 가격에 잘 샀어요'],
 ['루즈 핏이네요~', '적당한 두께~ 얇은 기모~ 따뜻하겠어요', '가격이 너무 착해요~', 'ㅎㅎ'],
 ['가 성비는 좋은데.. 색감도 훌륭 이뻐요', '입었을 때도 핏이 엄청 이뻐요..', '제가 찾던 옷입니다'],
 ['색상도 이쁘고 두루두루 잘 입을 거 같아요'],
 ['저렴한데 이쁘네요.', '편하게 잘 입고 다닐 수 있겠어요.', '약간 까 칠거리 긴해요'],
 ['가격대비 정말 좋은 상품입니다.', '재질도 좋고 디자인도 예쁘네요.'],
 ['재질도 너무 따갑고 사이즈도 작게 나와 입을 수가 없네요',
  'ㅜ 금액이 저렴해서 반품 않고 누구 주고 싶어도 촉감이 너무 따가워 줘도 욕먹을 거 같아서 주지도 못하고 그냥 반품해야 할 거 같네요',
  'ㅜ'],
 ['가격대비 너무 좋은 상품입니다.',
  '1+1 최 곱니다.',
  '딸아이 입고 넘 좋아합니다.',
  '사이즈 큰 거 미리 추가 주문합니다.'],
 ['기대 없이 주문했는데 품질이 완전 괜찮은 옷이네요~', '원 닥 톡톡 하구 안에는 기모처리되어 있구 완전 괜찮은 옷입니다', '^^'],
 ['남편도 착용감이 편하다 하고 간 절기 입기 좋아해요'],
 ['따뜻하고 좋은 제품, 가성 비도 좋네요~'],
 ['질이 좋아요', '좀 늘어지긴 하는데 괜찮아요', '편하게 입을 것 같아요'],
 ['화면보다 색상이 더 좋아요', '그리고 사이즈도 잘 맞네요.'],
 ['핏이 이쁩니다.',
  '혹시나 중고생 딸들에게 입을래?',
  '하며 물어보니... 한 개씩 챙기네요..',
  '엉덩이 살짝 가려 주고 짜임이 이뻐 올봄에 잘 입을 것 같습니다.',
  '생각보다 핑크가 화 사해서 많이 입을 것 같습니다.',
  '색상 다 이쁩니다.'],
 ['옷 자체는 예쁘지만 너무 느슨하고 니트가 꼼꼼 하지 못하고 힘이 없어요',
  '그리고 세가 지중 한 색은 옷 사이즈가 완전 작아요',
  '귀찮아 그냥 입 을려 고요'],
 ['디자인이 이뻐요', '소매 길이도 길고 날씬해 보이고 색상도 이뻐요', '딸이랑 나눠 입으려 입었어요'],
 ['3 종 다 색상도 이쁘고 디자인도 좋은데 사이즈가 크게 나왔어요', '어깨선도 내려오고 품이 너무 커요.'],
 ['개봉 시 냄새가 많이 나요 옷 품질은 좋아요'],
 ['색상도 이쁘고 디자인도 좋은데 어깨선이 넘 오버 핏이네요.',
  '품도 넘 크고.., 싸이즈 하나 줄여 재 주문합니다.',
  '그 정도로 다른 건 다 맘에 들어요',
  '사 이즈 넉넉하니 정 사이즈 추천합니다~',
  '^^ 참고로 두께 감이 있어 날씬해 보여요~'],
 ['통통 66 여유있게 맞아요', '따뜻하고 디자인이 예쁘네요'],
 ['조카딸아이가 코랄핑크가 맘에 든다고 하여 구매했는데 오늘 받고 바로 입어 보네요',
  '색상이 넘 맘에 든대요',
  '나머지 두 가지 색은 제가 입기로 했습니다',
  '^^ 보통 66 사이즈 입는데 90 사이즈도 조금 여유있게 잘 맞네요',
  '사 이즈 크게 나왔나',
  '봅니다'],
 ['일단은 택이 네이비 색 옷에만 있어요~',
  '옷상태를 봐서도 왠지 반품 물건 느낌에 기분이 좀 그렇더라구요.',
  '원단은 괜찮은 느낌이구 디자인은 많이 박시하고 롱합니다.',
  '참고로 160cm 55 사이즈 구입했구요.',
  '키가 좀 크신 분들에 겐 괜찮을 듯 합니다.',
  '조금 실망스럽지만 반품 귀찮아 입으려고요.'],
 ['가격대비 만족스러워요.',
  '한 가지 아쉬운 점은 55로 주문했는데, 티셔츠 사이즈가 제 각각이네요.',
  '같은 55로 보내주신 것 같은데 .. ㅠㅠ 그래서 좀 넉넉하게 나온 것은 엄마 두려요~~'],
 ['디자인, 색상 다 맘에 들어요.', '세탁 후 모양 변형과 보풀만 잘 안 생기면 좋겠어요.'],
 ['제 질도 좋고 사이즈도 잘 맞고. 따뜻하니 너무 좋아요'],
 ['디 잔인 무난해서 데일리룩으로 입기 좋아요', '팔이 총기 장 대비 쫌 긴 것 같아서 아쉽네요'],
 ['품질은 그런 데로 괜찮은데 좀앏아서 봄에 나 날이 따뜻해 지먼 입어야 할 거 같아요~'],
 ['가 성비 짱!! 색 상이 너무 맘에 들고 디자인도 이뻐요 ~~'],
 ['간 절기 입기 딱 좋아요',
  '재질도 괜찮고 66 사이즈 딱 맞네요',
  'ㅋ 엉덩이 길이 소매 길이도 이쁘고 전 목도 안 답답하고좋으네요'],
 ['재질이 넘 좋아요', '보풀이 날 것 같지 않아요', '그러면서도 부드럽고 몸에 착 감기는 게 너무 예쁩니다'],
 ['옷을 입었을 때 촉감도 부드럽고 목을 반정도 감 싸 주니 따뜻하고 몸에 살짝 붙는 것 같아 보이지만 여유 감도 있고 예뻐요~~'],
 ['44 사이즈가 55 붙는 사이즈네요~ 저는 카라 있는 게 제일 예쁘고 두께 감도 괜찮구요',
  '그 외 블랙, 회색, 레드 은 약간 얇고 진짜 이너로 입기에는 괜찮은 고거 같은데... 레드가 좀 얇은 감이 입고 사이즈가 아주 조금씩 차이 납니다',
  '가격대비 만족합니다!!!'],
 ['아가타 홈쇼핑에 방송하는 거치고 받아 보니 싼 티가 넘 많이 나네요',
  '그냥 싼 맛에 입을라고',
  '이 가격에 3개면 그냥 입을 만하니 간요'],
 ['가격대비 편하고 예쁘네요.',
  '골프 옷보다는 평상시 요즘 날씨에 딱 입기 좋은 것 같아요.',
  '3 종 모두 맘에 듭니다.',
  '잘 입을께요.'],
 ['가격대비 괜찮아요', '편하게 입기는 좋은데 기존 아가타보다는 소재가 좀 검은색은 애매하고 타이트 하네요'],
 ['옷이 예쁘고 핏도 좋고 소매가 조금 깅어요 잘 입 늘께요'],
 ['엄청 고급스럽진 않고, 그냥 무난합니다.',
  '청바지랑 같이 입기 편하겠어요.',
  '단추나 장식 박음질이 꼼꼼 하지 않고 많이 덜렁대서 한번 다시 박음질 해야겠어요. 그래도 튀지 않고 여기저기 편하게 잘 입을 거 같아 구매합니다.'],
 ['니트 하나하나 다~ 디자인이 이쁘네요~', '착용 감도 편하고. 싸이즈도 정 싸이즈라', '이뻐요~'],
 ['상품평 없어서 별 기대 없이 주문햇는데 배송도 빠르고 재질도 따뜻할 거 같아 좋네요',
  '보풀 걱정이 되 긴하지만 조심 히 입어야 죠 머...'],
 ['색상선택 앞두고 한참 고민했는데 ^^ 핑크. 와인 배색도 좋고 화면보다 색상이 더 예뻐요.',
  '한 사이즈 크게 했더니 더 좋은 것 같아요.'],
 ['원단이 부드럽고 실용적입니다'],
 ['시어머님 선물로 사 드렸는데 너무 너무 마음에 드셔 하네요.',
  '니트 지만 안에 얇은 기모 처리가 되어 있어 따뜻하니 바람도 안 들어 올 꺼 같다며 좋아하셔요',
  'ㅎㅎ'],
 ['서 이즈는 잘 맞는데 소매랑 옆구리부분이 한번 입었는데도 보풀이 많이 생겼어요.', '품질이 좀 아쉬워요'],
 ['사이즈도 딱 맞고 정말 따뜻해요.', '디자인도 예뻐서 색깔 별로 돌아가며 계속 입고 있어요.', '자켓도 예쁘고 따뜻합니다.'],
 ['바람막이 자켓은 괜찮은데 티셔츠는 뭔 가 불편하고 부피감이 있어 실물보다 살쪄 보입니다.',
  '품질이나 원단으로만 보면 괜찮은 편입니다.'],
 ['사이즈며 너무 좋습니다', '보기보다 두툼하여 추위 걱정은 없을 꺼 같구요', '다만 팔 길이가 조금 길어 살짝아쉽정도네요'],
 ['자켓은 생각보다 얇은 편이었고 .3 종 티셔츠는 . 품질이 가격 만큼이 네 여 ㅠㅠ. 저렴한 가격에. 막 입긴 좋을 듯요'],
 ['가격대비 퀄리티도 좋고 보온성 완 젼 좋아요.', '피부에 닿는 느낌 또한 너무 포근합니다.'],
 ['나이 드니 살집이 많아 져서 빅 사이즈 골프 웨어 찾기 힘들고, OOO 니트는 사이즈가 안성맞춤 이네요.',
  '추울 때 제외하고는 티셔츠 입고 착용해도 무난해요.',
  '봄. 가을 초겨울에도 착용 가능해요'],
 ['쟈켓은 생각보다 조금 얇지만 티셔츠는 도톰하서 따뜻하니 좋아요~~'],
 ['이동 수 골프 니트 스윙 자켓 바람막이가 기모의 따뜻함을 보호해 주니 더욱 따뜻하고 포근합니다.',
  '저렴한 가격에 제품의 만족감까지 대만족입니다.'],
 ['가격은 저렴한데 구성에서 니트 티는 싼 티가 나요 바람막이 때문에 구입했으니 다른 건 사은품정도로 생각하고 입으려구요 입어 보니 보풀 때문에 못 입을 정도네요 반품은 어렵다고',
  '하고 보풀 제거기가 고장날 정도로 보풀 뜯어 가며 입는데 곧 버려야 할 꺼 같아요',
  '상품이 불량인 듯 제품 전체가 불량인 듯해요'],
 ['디자인도 좋고 품질이 가격대비 너무 좋아요~~', '언니에게 선물해 주었는데 너무 좋다 고 극찬을 해 주네요'],
 ['색깔 디자인은 괜찮은데 옷감질이 좀 그렇네요'],
 ['비싼 돈 주고 이동 수 골프 웨어 민 구입했었는데 싸고 질 좋은 것을 질 선택했습니다.', '맘에 들어요.'],
 ['따뜻하고 디자인이 예쁜 거 저렴하게 잘 사서 아주 잘 입고 다닙니다'],
 ['상품 받아 확인하니 디자인이 깔끔하고 심플해서 만족입니다', '가격대비 구성도 좋고요'],
 ['가 디 건은 얇은 듯 하고 약간 크고 티는 생각보다 두꺼워서 따뜻하게 입을 수 있을 듯 해요'],
 ['레드 이쁘네요', '티셔츠 목부분이 신축성이 없어서 머리 큰사람은 엄청 힘드네요 ....', '그래도 저렴하고 좋으네요'],
 ['자켓 디자인이 가장 맘에 들구요, 기모 티셔츠도 활용도가 높네요~', '♡'],
 ['며칠 입은 것도 아니고 하루 입었는데 티세츠에 보풀이 심하네요',
  '살 짝 라인도 있으면 좋겠는데 박스 스타일에 천이 엉 아니에요~~',
  '입으면 너무 보기 싫어요'],
 ['부드럽고 감촉 어 좋아요', '핏이 좋아서 색상과 조화롭네요'],
 ['넉넉한 길이가 우선 맘에 들고요', '가볍고 따뜻해서 자주 입고 있어요.'],
 ['촉감 좋고 사이즈 딱이 예요 기모가 들어서 한겨울에도 든든할 것 같구요',
  '그런데 봉제 선 라인이 투박해서 어깨라인이 각져 보이고 빨간색 티는 목이 늘어나지 않아 입 기가 매~ 우 불편 해요 전체적으로 스판이 조금부족해서 활동하기 불편한 듯해요',
  '딱 가격 만큼의 가치인 듯해요'],
 ['티셔츠는 정말 품질이 아니네요', '신축성도 없고 타이트 해요 답답 하구요'],
 ['제품 디자인이 아주 깔끔하고 고급스러워요'],
 ['친정 아빠 주문해 드렸는데 티셔츠가 가볍고 따뜻하고 좋아하시네요'],
 ['사이즈도 정 사이즈, 스타일도 좋고 오랫만에 득 템 하였습니다'],
 ['날씬하게 보이고 싸게 잘 구입했어요', '감사합니다', 'ㅡ'],
 ['디자인 품질 가격 모두 만족합니다~'],
 ['가격도 착하고 입은 모습도 이뻐서 좋아요.', '옷감이 좀더 부드러우면 좋을 것 같아요.'],
 ['재질도 두껍고 루즈 핏이면 자칫 뚱뚱 해 보일 수 있는데 날씬해 보입니다.'],
 ['재질도 두툼하고 착용감이 편해요', '특히 바지가 완전 편합니다', 'ㅎㅎ'],
 ['ㅣ잘받았구요 가 디 건이 넘 펑퍼짐해서 뚱뚱 해 보이는데 목도리로 사용하니 좋은 것 같아 그냥 입으려구요 가격대비 착해서요'],
 ['아주 저렴하게 편하고 색상도 맘에 들어요'],
 ['셔츠가 보풀이 좀 생기네요', '가 디 건은 가 성비 좋네요'],
 ['핏이 너무 예뻐요',
  '디자인이 세련되고 편리하게 여러모로 잘 코디가 됩니다',
  '좋은 상품감사 드려요 좋은 가격에 좋은 품질 넘 감사 드려요 잘 유용하게 입고 있어요'],
 ['니트도 적당한 길이 감에 소재도 나쁘지 않구요',
  '판 쵸 숄 가 디 건은 편하게 걸치기 좋고 은근 따뜻해요',
  'ㅎㅎ 가 성비 최고 상품 같아요',
  '^^'],
 ['간 절기에 필요한 제품이고 예쁘기까지 하네요.'],
 ['간 절기 입기에 너무 좋네요', '두께가 좋아서요 만족합니다'],
 ['약간 크게 나와 딱 맞게 입으려 면 한 사이즈 작게 입어도 좋을 것 같네요',
  '색상 및 디자인 맘에 드네요',
  '가격대비 재질은 좋아요',
  '숄만가지고도 봄까지 유용하게 입을 것 같아요'],
 ['따뜻하고 디자인도 고급스럽고 가 성비 최고야요'],
 ['안에 니트 티 색상은 화면과 달리 연한 핑크 라 더 맘에 드네요',
  '타 홈쇼핑에서 7 만원 대에 방송했는데 정말 가격이 착하네요',
  '사이즈도 여유있고 괜찮은 제품입니다',
  '정말 가격 착하네요'],
 ['색상이 예쁘게 나왔어요.', '키가 커서 인지 길이는 조금 짧네요.', '분위기가 나서 좋아요.'],
 ['제품의 색상은 만족하나 정 사이즈에 비해 큽니다'],
 ['포근하고 입고 벗기간 편하면 무엇보다 활용도가 좋아요', '어떤 옷에도 매치하기 좋은 물건입니다'],
 ['ㅇ ㅇ쇼핑에서 첨으로 구매했어요!',
  '니트 티는 좀 얇아서 봄 가을에 입으려구요 판쵸는 아이보리보다 블랙 니트 티에 입으니 디자인이 더 고급스럽고 멋스럽네요!',
  '저렴한 가격으로 맘에 드는 옷 샀어요'],
 ['날씬한 사람에 겐 예쁠 것 같은데 저에 겐 좀 부 하게 보이네요', '그래도 적립금으로 저렴하게 구입했습니다', '잘 입을께요~'],
 ['추운 겨울 끝날 무렵이면 옷 입기 애매한 데 겉에 편하게 걸치고 나갈 수 있을 것 같아서 미리 구매했는데 길이가 엄청 맘에 드네요'],
 ['기대 이상이네요', '핏도 예쁘고 사이즈도 딱 좋아요'],
 ['숄 가 디 건 하나쯤 가지고 싶은 아이인데 때마침 좋은 옷 가지게 되어 좋습니다', '핏도 좋고 착용감이 편하고 맘에 듭니다'],
 ['소재가 그럭저럭 이네요', '저렴한 딱 그 가격'],
 ['블랙 색상 풀오버는 아이보리 정도 되겠지 했는데 베이지에 가까워서 다른 블랙 티셔츠랑 입어야 할 것 같아요.',
  '일단 디쟈인은 좋은데 원단이 가격 만큼인 듯 같네요',
  'ㅜㅜ'],
 ['판 쵸 숄 가 디 건, 니트 풀오버 모두 디자인은 물론 색상과 옷감의 품질이 좋고 핏도 매우 만족하여 다른 색상으로 한 세트 더 주문하고 싶은 마음이네요.'],
 ['가 성비 좋고, 입었을 때 핏도 맘에 들고 다른 옷과도 코디가 잘되서 맘에 들어요.', '지인에게 추천 했어요'],
 ['구성 맘에 들어요~', '디자인이 체형 커버도 되구요.가', '디 건으로 여러 활용할 수 있네요..', '잘 입을께요'],
 ['가 성비 짱입니다!!', '니트 촉감도 좋아요~~'],
 ['봄이 되면 간 절기에 편하게 입고 일할 수 있는 편리성과 각각 옷을 다양하게 코디하기에 좋을 듯합니다',
  '티는 간단히 입고 다른 옷에 코디가 가능하고 ᆢ 윗 옷은 어떤 색깔과도 잘 맞아 멋 낼 때 입을 수 있는 코디 형 스카프 같은 느낌입니다',
  'ᆢ 잘 입을께요'],
 ['소재가 너무 고급 지고 편하고 핏 더 멋스럽네요~'],
 ['디자인이 예뻐서 직장 동료가 바로 두개 더 구매 합니다.',
  '네이비도 디자인이 무난하고 안에 입는 쉐터도 넉넉하고 좋아요.',