### 데이터의 분할
- 분석 모델을 학습하고 성과를 확인하기 위해서 데이터를 Train, Test 세트로 나눠주는 작업 
- 독립 변수(X) -> 문제 , 종속 변수(y) -> 정답
- 독립 변수와 종속 변수 모두 Train, Test 데이터로 나눠준다. 
- 분석 방법이나 데이터의 양에 따라서 Train, Validation, Test로 나눠주는 경우도 발생 
- 데이터를 분할하는 일반적인 비율 
    - Train : Test = 7 : 3 // 8 : 2
        - 가장 일반적인 분할 비율
    - Train : Validation : Test = 6 : 2 : 2
        - 데이터의 양이 많은 경우 검증 셋을 생성하여 2번에 검증 작업 
    - kfold를 이용하면 여러번의 작업을 하여 검증이 가능
    - 유의할 점 
        - 데이터의 불균형 문제.
        - 데이터의 균형을 알맞게 분할하는 작업이 필요
- sklearn안에 train_test_split() 함수를 이용하여 데이터를 분할
    - train_test_split( X, y, test_size = None, random_state = None, shuffle = True, stratify = None )
        - X : 독립 변수( 문제 )
        - y : 종속 변수( 정답 )
        - test_size : 테스트데이터의 비율 (0부터 1사이의 값)
        - random_state : 임의의 데이터를 추출하는 과정에서 seed 값을 지정 (같은 값을 지정하면 규칙이 생성되어 같은 데이터를 확인)
        - shuffle : 데이터를 섞을것인가 ( 시계열 데이터셋인 경우에는 False )
        - stratify : 특정 변수를 지정하면 지정한 변수를 기준으로 하여 계층화 되어 해당 변수의 비율을 유지하도록 데이터 분할

In [1]:
import pandas as pd 
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [2]:
# 샘플 데이터셋 로드 
iris_data = load_iris()

In [3]:
iris_data['frame']

In [4]:
# 데이터프레임으로 변경 
iris = pd.DataFrame(iris_data['data'], columns = iris_data['feature_names'])

# target 데이터 데이터프레임에 추가 
iris['class'] = iris_data['target']

iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),class
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [5]:
# target 데이터들을 변환 
iris['class'] = iris['class'].map(
    lambda x : iris_data['target_names'][x]
)

In [6]:
iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),class
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [7]:
# class 컬럼의 데이터의 빈도수를 확인 
iris['class'].value_counts()

class
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [8]:
# 종속 변수, 독립 변수 데이터를 나눠서 train_test_splot() 입력 
x = iris.drop('class', axis=1)
x

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [9]:
y = iris['class']
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: class, Length: 150, dtype: object

In [10]:
# train_test_split() --> 결과물( train_x, test_x, train_y, test_y )
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size= 0.3, random_state=42
)

In [13]:
# 데이터의 개수를 확인 
print(f"X_trian : {X_train.shape}, X_test : {X_test.shape}")
print(f"y_train : {y_train.shape}, y_test : {y_test.shape}")

X_trian : (105, 4), X_test : (45, 4)
y_train : (105,), y_test : (45,)

In [15]:
y_train.value_counts()

class
versicolor    37
virginica     37
setosa        31
Name: count, dtype: int64

In [16]:
# shuffle을 False로 바꿔서 사용하게 되면?
X_train2, X_test2, y_train2, y_text2 = train_test_split(
    x, y, test_size=0.3, shuffle=False
)

In [17]:
X_train2.shape

(105, 4)

In [18]:
y_train2.value_counts()

class
setosa        50
versicolor    50
virginica      5
Name: count, dtype: int64

In [22]:
iris.loc[: 104, 'class'].value_counts()

class
setosa        50
versicolor    50
virginica      5
Name: count, dtype: int64

In [23]:
# 데이터 비율에 맞춰서 분할
X_train3, X_test3, y_train3, y_test3 = train_test_split(
    x, y, test_size=0.3, random_state=42, stratify=y
)

In [24]:
X_train3.shape

(105, 4)

In [26]:
y_train3

98     versicolor
68     versicolor
19         setosa
143     virginica
99     versicolor
          ...
37         setosa
79     versicolor
33         setosa
94     versicolor
3          setosa
Name: class, Length: 105, dtype: object

In [27]:
y_train3.value_counts()

class
versicolor    35
setosa        35
virginica     35
Name: count, dtype: int64

In [31]:
# 계층화 작업을 하면 shuffle 무조건 True로 사용
# X_train4, X_test4, y_train4, y_test4 = train_test_split(
#     x, y, test_size=0.3, shuffle=False, stratify=y
# )

In [32]:
y_train2

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
100    virginica
101    virginica
102    virginica
103    virginica
104    virginica
Name: class, Length: 105, dtype: object