In [1]:
import pandas as pd

In [16]:
# csv 폴더 안에 있는 corona.csv 파일 로드 
# 현재 작업중인 폴더(./)(생략이 가능) -> 상위 폴더로 이동(../) 
# -> csv 하위 폴더로 이동(csv/) -> corona.csv
# 상대경로는 내 파일의 위치에서부터 시작
corona = pd.read_csv("../csv/corona.csv")

In [3]:
# 데이터의 확인 : head(), tail()
corona.head()

,Unnamed: 0,createDt,deathCnt,decideCnt,seq,stateDt,stateTime,updateDt,accExamCnt,accDefRate
0,0,2022-06-08 09:09:05.982,24305,18188200,904,20220608,00:00,NaN,NaN,NaN
1,1,2022-06-07 09:09:00.897,24299,18174842,903,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
2,2,2022-06-06 09:00:06.734,24279,18168670,902,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
3,3,2022-06-05 08:53:19.426,24258,18163648,901,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
4,4,2022-06-04 08:56:49.219,24238,18153814,900,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN

In [4]:
corona.tail()

,Unnamed: 0,createDt,deathCnt,decideCnt,seq,stateDt,stateTime,updateDt,accExamCnt,accDefRate
815,815,2020-03-14 00:00:00.000,72,8086,55,20200314,00:00,2021-10-07 10:30:51.51,261335.0,3.318000
816,816,2020-03-13 00:00:00.000,67,7979,54,20200313,00:00,2021-10-07 10:30:51.51,248647.0,3.458499
817,817,2020-03-12 00:00:00.000,66,7869,53,20200312,00:00,2021-10-07 10:30:51.51,234998.0,3.621744
818,818,2020-03-11 00:00:00.000,60,7755,52,20200311,00:00,2021-10-07 10:30:51.51,222395.0,3.804175
819,819,2020-03-10 00:00:00.000,54,7513,51,20200310,00:00,2021-10-07 10:30:51.51,210144.0,3.919308

In [8]:
# 데이터프레임에서 컬럼들의 목록 확인 
# DataFrame라는 Class에는 3개 변수 -> values, index, columns
corona.columns

Index(['Unnamed: 0', 'createDt', 'deathCnt', 'decideCnt', 'seq', 'stateDt',
       'stateTime', 'updateDt', 'accExamCnt', 'accDefRate'],
      dtype='str')

In [17]:
# Unnamed: 0 컬럼은 인덱스로 사용이 됬었구나 -> 필요가 없다. -> 해당 컬럼의 데이터는 제거
# seq 컬럼의 데이터는 게시글의 번호 -> 제거 
# 특정 데이터를 제거(drop())
# dropna() -> 매개변수 축 설정(axis) -> 인덱스를 제거할것인가? 컬럼을 제거할것인가?
#           -> 매개변수 inplace -> 원본의 데이터를 변화 시킬것인가
#           -> 결측치를 제거한다
# drop() -> axis, inplace 매개변수 존재  
#       -> 첫번째 인자는 어떠한 것을 제거할것인가?
#       -> drop() 함수에서 기본 설정은 인덱스를 제거 
corona.drop(
    ['Unnamed: 0','seq'], axis=1, inplace=True
)
# 우리가 제거할 컬럼의 개수가 2개
# drop(inplace=True)의 함수를 실행하면 -> 첫번째 실행에서 정상 처리가 되더라도 
# -> 같은 블록을 다시 실행하면 에러 발생 ( 해당 데이터가 제거되고 다시 제거하려니 없다. )

In [18]:
corona.head(1)

,createDt,deathCnt,decideCnt,stateDt,stateTime,updateDt,accExamCnt,accDefRate
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN

In [ ]:
# 컬럼의 이름을 변경 
# case1 : rename() 함수를 이용하여 컬럼의 이름을 변경 
# 특정 컬럼의 이름을 변경할때 사용
corona.rename(
    columns = {
        'createDt' : '등록일시', 
        'deathCnt' : '총사망자', 
        'decideCnt' : '총확진자', 
        'stateDt' : '기준일', 
        'stateTime' : '기준시간', 
        'updateDt' : '수정일시', 
        'accExamCnt' : '누적의심자', 
        'accDefRate' : '누적확진율'
    }
)

In [23]:
# case2 : Class 내부의 columns 변수에 접근해서 다른 데이터를 대입 
# ( 데이터를 변경하기 전에 확인은 불가능 ) 
# -> 이 방법은 모든 컬럼의 이름을 변경할때 주로 사용
# 주의사항 : 컬럼의 개수가 같은 자료형 데이터를 대입 (길이가 다르면 에러 발생)
corona.columns = ['등록일시', '총사망자', '총확진자', '기준일', 
                  '기준시간', '수정일시', '누적의심자', '누적확진율']

In [24]:
corona.head(1)

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN

In [ ]:
corona.head(10)

In [26]:
# 데이터를 확인하는 방법 : info(), isna().sum(), describe()
corona.info()

<class 'pandas.DataFrame'>
RangeIndex: 820 entries, 0 to 819
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   등록일시    820 non-null    str
 1   총사망자    820 non-null    int64
 2   총확진자    820 non-null    int64
 3   기준일     820 non-null    int64
 4   기준시간    820 non-null    str
 5   수정일시    817 non-null    str
 6   누적의심자   692 non-null    float64
 7   누적확진율   623 non-null    float64
dtypes: float64(2), int64(3), str(3)
memory usage: 51.4 KB