In [ ]:
import pandas as pd

In [ ]:
# csv 폴더 안에 tran_1.csv, tran_2.csv 파일을 로드 
tran_1 = pd.read_csv("../csv/tran_1.csv")
tran_2 = pd.read_csv("../csv/tran_2.csv")

In [ ]:
tran_1.head(1)

In [ ]:
tran_2.head(1)

In [ ]:
tran_1.info()

In [ ]:
tran_2.info()

In [9]:
# tran_1, tran_2 데이터를 결합 
    # 두개의 데이터프레임은 테이블의 구조가 같은 형태 
    # 단순한 행 결합 
    # 두개의 데이터프레임이 행 결합을 하면 rows의 개수는? -> 5000 + 1786 = 6786
# concat() 함수 이용
# pandas 안에 concat 함수 호출 --> 원본의 데이터라는 개념이 존재 x -> 
# 결과를 저장하려면 새로운 변수에 대입 
tran = pd.concat(
    [ tran_1, tran_2 ], axis = 0, ignore_index= True
)

In [10]:
tran.info()

<class 'pandas.DataFrame'>
RangeIndex: 6786 entries, 0 to 6785
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  6786 non-null   str
 1   price           6786 non-null   int64
 2   payment_date    6786 non-null   str
 3   customer_id     6786 non-null   str
dtypes: int64(1), str(3)
memory usage: 212.2 KB

In [11]:
# tran_d_1.csv, tran_d_2.csv 파일을 로드 
tran_d_1 = pd.read_csv("../csv/tran_d_1.csv")
tran_d_2 = pd.read_csv("../csv/tran_d_2.csv")

In [12]:
tran_d_1.head(1)

   detail_id transaction_id item_id  quantity
0          0    T0000000113    S005         1

In [13]:
tran_d_2.head(1)

   detail_id transaction_id item_id  quantity
0       5000    T0000004870    S002         3

In [14]:
tran_d_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       5000 non-null   int64
 1   transaction_id  5000 non-null   str
 2   item_id         5000 non-null   str
 3   quantity        5000 non-null   int64
dtypes: int64(2), str(2)
memory usage: 156.4 KB

In [15]:
tran_d_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 2144 entries, 0 to 2143
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       2144 non-null   int64
 1   transaction_id  2144 non-null   str
 2   item_id         2144 non-null   str
 3   quantity        2144 non-null   int64
dtypes: int64(2), str(2)
memory usage: 67.1 KB

In [18]:
# tran_d_1, tran_d_2 데이터프레임을 단순 행 결합 
tran_d = pd.concat(
    [tran_d_1, tran_d_2], axis=0, ignore_index=True
)

In [19]:
tran_d.info()

<class 'pandas.DataFrame'>
RangeIndex: 7144 entries, 0 to 7143
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       7144 non-null   int64
 1   transaction_id  7144 non-null   str
 2   item_id         7144 non-null   str
 3   quantity        7144 non-null   int64
dtypes: int64(2), str(2)
memory usage: 223.4 KB

In [20]:
tran.head(1)

  transaction_id   price         payment_date customer_id
0    T0000000113  210000  2019-02-01 01:36:57    PL563502

In [21]:
tran_d.head(1)

   detail_id transaction_id item_id  quantity
0          0    T0000000113    S005         1

In [ ]:
tran_d['transaction_id'].value_counts()

In [23]:
tran['transaction_id'].describe()

count            6786
unique           6786
top       T0000000113
freq                1
Name: transaction_id, dtype: object

In [28]:
# tran과 tran_d 데이터프레임을 결합 
# 테이블의 구조는 다르게 구성 -> 단순한 행결합 불가능 
# 인덱스의 개수가 다르다 -> 6786 // 7144개의 데이터 
# 두개의 데이터프레임이 공통적으로 가지고 있는 데이터 컬럼은 존재하는가?
    # transaction_id 컬럼은 공통적으로 가지고 있다 -> 조인결합이 가능
# tran의 인덱스의 수는 6786개
# tran_d의 인덱스의 수는 7144개 
    # 두개의 데이터프레임을 조인 결합 했을때 -> 인덱스의 수는 어떻게 나올것인가?
    # 6786 // 7144 --> how 에 따라 다르게 나올것인가?
transaction = pd.merge(
    tran, tran_d, 
    # 조건 ( 두개의 데이터프레임이 공통적으로 가지고 있는 컬럼의 이름 )
    on = 'transaction_id',
    # 결합의 방식은 어떻게 할것인가?
    how = 'outer'
)

In [30]:
# 총 4개의 데이터 파일을 하나의 데이터프레임으로 결합 
transaction.head(1)

,transaction_id,price,payment_date,customer_id,detail_id,item_id,quantity
0,T0000000113,210000,2019-02-01 01:36:57,PL563502,0,S005,1

#### 데이터 결합 연습 
1. transaction 데이터프레임과 csv 폴더 안에 item_master 파일을 로드하여 2개의 데이터프레임을 결합 
2. 결합된 데이터에 csv 폴더에 customer_master 파일을 로드 하여 데이터프레임을 결합 
3. payment_date 컬럼의 데이터를 시계열데이터로 변환 ( to_datetime(스리즈) )

In [31]:
# 파일 로드 
item_master = pd.read_csv("../csv/item_master.csv")
customer_master = pd.read_csv("../csv/customer_master.csv")

In [32]:
item_master.head(1)

  item_id item_name  item_price
0    S001      PC-A       50000

In [33]:
customer_master.head(1)

,customer_id,name,class,gender,start_date,end_date,campaign_id,is_deleted
0,OA832399,XXXX,C01,F,2015-05-01 00:00:00,NaN,CA1,0

In [34]:
item_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item_id     5 non-null      str
 1   item_name   5 non-null      str
 2   item_price  5 non-null      int64
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [35]:
customer_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 4192 entries, 0 to 4191
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  4192 non-null   str
 1   name         4192 non-null   str
 2   class        4192 non-null   str
 3   gender       4192 non-null   str
 4   start_date   4192 non-null   str
 5   end_date     1350 non-null   str
 6   campaign_id  4192 non-null   str
 7   is_deleted   4192 non-null   int64
dtypes: int64(1), str(7)
memory usage: 262.1 KB

In [36]:
transaction.info()

<class 'pandas.DataFrame'>
RangeIndex: 7144 entries, 0 to 7143
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  7144 non-null   str
 1   price           7144 non-null   int64
 2   payment_date    7144 non-null   str
 3   customer_id     7144 non-null   str
 4   detail_id       7144 non-null   int64
 5   item_id         7144 non-null   str
 6   quantity        7144 non-null   int64
dtypes: int64(3), str(4)
memory usage: 390.8 KB

In [39]:
# transaction , item_master  조인 결합 -> 공통 컬럼은 item_id
df = transaction.merge(
    item_master, 
    on = 'item_id', 
    how = 'inner'
)

In [ ]:
df.info()
# item_master에서 결합된 컬럼 item_name, item_price의 결측치가 존재하지 않는다
# 같은 집합 : item_id 기준으로 inner 결합 -> 인덱스도 유지 / 결측치도 존재x

In [45]:
# df와 customer_master 조인 결합  -> 조건 customer_id
df = pd.merge(
    df, customer_master, 
    on = 'customer_id', 
    how = 'inner'
)

In [54]:
# 시계열데이터 payment_date를 컬럼을 타입을 변경 
# 문자를 시계열로 변경 ( datetime.strptime() // to_datetime() )
pd.to_datetime(df['payment_date'])

0      2019-02-01 01:36:57
1      2019-02-01 01:37:23
2      2019-02-01 02:34:19
3      2019-02-01 02:47:23
4      2019-02-01 04:33:46
               ...
6064   2019-07-31 20:28:20
6065   2019-07-31 21:17:39
6066   2019-07-31 21:52:48
6067   2019-07-31 23:35:25
6068   2019-07-31 23:41:38
Name: payment_date, Length: 6069, dtype: datetime64[us]

In [48]:
# datetime 라이브러리의 strptime()을 이용하여 데이터 타입 변환 
from datetime import datetime

In [50]:
df['payment_date'][0]

'2019-02-01 01:36:57'

In [ ]:
# datetime 안에 strptime() 함수는 pandas에 to_datetime()과는 다르게 스리즈 형태 변환 불가능
# datetime.strptime(df['payment_date'], '%Y-%m-%d %H:%M:%S')
# 스리즈 데이터에서 value들을 하나씩 뽑아서 함수에 넣는다 map()
df['payment_date'].map(
    # x에 대입이 되는 데이터는 문자
    lambda x : datetime.strptime(x, '%Y-%m-%d %H:%M:%S')
)

In [ ]:
# 스리즈 데이터에서 문자열 함수를 사용하기 위해 
    # 1. 반복문 사용
    # 2. map() + lambda
    # 문자열 함수를 사용할수 있도록 pandas에서 제공한 Series.str (StringMethods)
# 스리즈에서는 시계열 함수를 사용할 수 있도록 문자열과 같이 DatetimeMethods 변환이 존재 
    # Series.dt --> 해당 데이터셋이 시계열로 시계열 함수

In [56]:
df['payment_date'] = pd.to_datetime(df['payment_date'])

In [57]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6069 entries, 0 to 6068
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  6069 non-null   str
 1   price           6069 non-null   int64
 2   payment_date    6069 non-null   datetime64[us]
 3   customer_id     6069 non-null   str
 4   detail_id       6069 non-null   int64
 5   item_id         6069 non-null   str
 6   quantity        6069 non-null   int64
 7   item_name       6069 non-null   str
 8   item_price      6069 non-null   int64
 9   name            6069 non-null   str
 10  class           6069 non-null   str
 11  gender          6069 non-null   str
 12  start_date      6069 non-null   str
 13  end_date        1978 non-null   str
 14  campaign_id     6069 non-null   str
 15  is_deleted      6069 non-null   int64
dtypes: datetime64[us](1), int64(5), str(10)
memory usage: 758.8 KB

In [ ]:
# 요일별 판매가 된 제품들의  총 판매 개수 합계가 어떻게 되는가?
# 요일이라는 새로운 변수를 생성 -> 시계열에서 요일만 따로 추출(strftime(%A|%a|%w))
df['요일'] = df['payment_date'].dt.strftime('%A')
# strftime(%w) -> 0(일), ...

In [ ]:
df['payment_date'].dt.weekday
# weekday -> 0(월), ...

In [74]:
df.head(1)

,transaction_id,price,payment_date,customer_id,detail_id,item_id,quantity,item_name,item_price,name,class,gender,start_date,end_date,campaign_id,is_deleted,요일
0,T0000000113,210000,2019-02-01 01:36:57,PL563502,0,S005,1,PC-E,210000,XX,C01,M,2018-07-01 00:00:00,NaN,CA1,0,Friday

In [75]:
# 요일, item_id를 기준으로 그룹화 -> quantity의 합산 
df[['요일', 'item_id', 'quantity']].groupby(['요일', 'item_id']).sum()

                   quantity
요일        item_id
Friday    S001          406
          S002          250
          S003          140
          S004          105
          S005          225
Monday    S001          363
          S002          201
          S003          132
          S004           97
          S005          207
Saturday  S001          367
          S002          182
          S003          141
          S004          102
          S005          231
Sunday    S001          390
          S002          236
          S003          121
          S004          121
          S005          210
Thursday  S001          334
          S002          206
          S003          128
          S004          103
          S005          227
Tuesday   S001          336
          S002          227
          S003          121
          S004          107
          S005          212
Wednesday S001          382
          S002          216
          S003           98
          S004          122
          S005          241