In [ ]:
import pandas as pd

In [ ]:
# csv 폴더 안에 tran_1.csv, tran_2.csv 파일을 로드 
tran_1 = pd.read_csv("../csv/tran_1.csv")
tran_2 = pd.read_csv("../csv/tran_2.csv")

In [ ]:
tran_1.head(1)

In [ ]:
tran_2.head(1)

In [ ]:
tran_1.info()

In [ ]:
tran_2.info()

In [9]:
# tran_1, tran_2 데이터를 결합 
    # 두개의 데이터프레임은 테이블의 구조가 같은 형태 
    # 단순한 행 결합 
    # 두개의 데이터프레임이 행 결합을 하면 rows의 개수는? -> 5000 + 1786 = 6786
# concat() 함수 이용
# pandas 안에 concat 함수 호출 --> 원본의 데이터라는 개념이 존재 x -> 
# 결과를 저장하려면 새로운 변수에 대입 
tran = pd.concat(
    [ tran_1, tran_2 ], axis = 0, ignore_index= True
)

In [10]:
tran.info()

<class 'pandas.DataFrame'>
RangeIndex: 6786 entries, 0 to 6785
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  6786 non-null   str
 1   price           6786 non-null   int64
 2   payment_date    6786 non-null   str
 3   customer_id     6786 non-null   str
dtypes: int64(1), str(3)
memory usage: 212.2 KB

In [11]:
# tran_d_1.csv, tran_d_2.csv 파일을 로드 
tran_d_1 = pd.read_csv("../csv/tran_d_1.csv")
tran_d_2 = pd.read_csv("../csv/tran_d_2.csv")

In [12]:
tran_d_1.head(1)

   detail_id transaction_id item_id  quantity
0          0    T0000000113    S005         1

In [13]:
tran_d_2.head(1)

   detail_id transaction_id item_id  quantity
0       5000    T0000004870    S002         3

In [14]:
tran_d_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       5000 non-null   int64
 1   transaction_id  5000 non-null   str
 2   item_id         5000 non-null   str
 3   quantity        5000 non-null   int64
dtypes: int64(2), str(2)
memory usage: 156.4 KB

In [15]:
tran_d_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 2144 entries, 0 to 2143
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       2144 non-null   int64
 1   transaction_id  2144 non-null   str
 2   item_id         2144 non-null   str
 3   quantity        2144 non-null   int64
dtypes: int64(2), str(2)
memory usage: 67.1 KB

In [18]:
# tran_d_1, tran_d_2 데이터프레임을 단순 행 결합 
tran_d = pd.concat(
    [tran_d_1, tran_d_2], axis=0, ignore_index=True
)

In [19]:
tran_d.info()

<class 'pandas.DataFrame'>
RangeIndex: 7144 entries, 0 to 7143
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       7144 non-null   int64
 1   transaction_id  7144 non-null   str
 2   item_id         7144 non-null   str
 3   quantity        7144 non-null   int64
dtypes: int64(2), str(2)
memory usage: 223.4 KB

In [20]:
tran.head(1)

  transaction_id   price         payment_date customer_id
0    T0000000113  210000  2019-02-01 01:36:57    PL563502

In [21]:
tran_d.head(1)

   detail_id transaction_id item_id  quantity
0          0    T0000000113    S005         1

In [ ]:
tran_d['transaction_id'].value_counts()

In [23]:
tran['transaction_id'].describe()

count            6786
unique           6786
top       T0000000113
freq                1
Name: transaction_id, dtype: object

In [ ]:
# tran과 tran_d 데이터프레임을 결합 
# 테이블의 구조는 다르게 구성 -> 단순한 행결합 불가능 
# 인덱스의 개수가 다르다 -> 6786 // 7144개의 데이터 
# 두개의 데이터프레임이 공통적으로 가지고 있는 데이터 컬럼은 존재하는가?
    # transaction_id 컬럼은 공통적으로 가지고 있다 -> 조인결합이 가능
# tran의 인덱스의 수는 6786개
# tran_d의 인덱스의 수는 7144개 
    # 두개의 데이터프레임을 조인 결합 했을때 -> 인덱스의 수는 어떻게 나올것인가?
    # 6786 // 7144 --> how 에 따라 다르게 나올것인가?
pd.merge(
    tran, tran_d, 
    # 조건 ( 두개의 데이터프레임이 공통적으로 가지고 있는 컬럼의 이름 )
    on = 'transaction_id',
    # 결합의 방식은 어떻게 할것인가?
    how = 'outer'
)