In [1]:
import pandas as pd

In [2]:
# csv 폴더 안에 있는 Sales Records.csv 파일 로드 
sales = pd.read_csv("../csv/Sales Records.csv")

In [3]:
# 데이터 파일을 로드했으면 확인 
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Region          10000 non-null  str
 1   Country         10000 non-null  str
 2   Item Type       10000 non-null  str
 3   Sales Channel   10000 non-null  str
 4   Order Priority  10000 non-null  str
 5   Order Date      10000 non-null  str
 6   Order ID        10000 non-null  int64
 7   Ship Date       10000 non-null  str
 8   Units Sold      10000 non-null  int64
 9   Unit Price      10000 non-null  float64
 10  Unit Cost       10000 non-null  float64
 11  Total Revenue   10000 non-null  float64
 12  Total Cost      10000 non-null  float64
 13  Total Profit    10000 non-null  float64
dtypes: float64(5), int64(2), str(7)
memory usage: 1.1 MB

In [4]:
sales.describe()

,Order ID,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
count,1.000000e+04,10000.000000,10000.000000,10000.000000,1.000000e+04,1.000000e+04,1.000000e+04
mean,5.498719e+08,5002.855900,268.143139,188.806639,1.333355e+06,9.382658e+05,3.950893e+05
std,2.607835e+08,2873.246454,217.944092,176.445907,1.465026e+06,1.145914e+06,3.775550e+05
min,1.000892e+08,2.000000,9.330000,6.920000,1.679400e+02,1.245600e+02,4.338000e+01
25%,3.218067e+08,2530.750000,109.280000,56.670000,2.885511e+05,1.647855e+05,9.832914e+04
50%,5.485663e+08,4962.000000,205.700000,117.110000,8.000512e+05,4.816058e+05,2.890990e+05
75%,7.759981e+08,7472.000000,437.200000,364.690000,1.819143e+06,1.183822e+06,5.664227e+05
max,9.999342e+08,10000.000000,668.270000,524.960000,6.680027e+06,5.241726e+06,1.738178e+06

In [5]:
# 데이터프레임의 상단의 5개의 데이터를 확인 
sales.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Sub-Saharan Africa,Chad,Office Supplies,Online,L,1/27/2011,292494523,2/12/2011,4484,651.21,524.96,2920025.64,2353920.64,566105.00
1,Europe,Latvia,Beverages,Online,C,12/28/2015,361825549,1/23/2016,1075,47.45,31.79,51008.75,34174.25,16834.50
2,Middle East and North Africa,Pakistan,Vegetables,Offline,C,1/13/2011,141515767,2/1/2011,6515,154.06,90.93,1003700.90,592408.95,411291.95
3,Sub-Saharan Africa,Democratic Republic of the Congo,Household,Online,C,9/11/2012,500364005,10/6/2012,7683,668.27,502.54,5134318.41,3861014.82,1273303.59
4,Europe,Czech Republic,Beverages,Online,C,10/27/2015,127481591,12/5/2015,3491,47.45,31.79,165647.95,110978.89,54669.06

### 연습 
1. 원본의 데이터의 복사본을 생성(df)
2. 'Order ID', 'Total Revenue', 'Total Cost', 'Total Profit', 'Oerder Priority' 컬럼을 제거
3. 컬럼의 이름을 변경 -> 대륙, 국가, 상품종류, 판매채널, 주문일자, 발송일자, 판매개수, 단가, 원가
4. 대륙, 국가를 기준으로 오름차순 정렬
5. 인덱스를 초기화하고 기존의 인덱스는 제거 
6. 파생변수 생성 
    - 총단가 = 단가 * 판매개수
    - 총원가 = 원가 * 판매개수
    - 총이윤 = 총단가 - 총원가