In [75]:
import re 
import pandas as pd 
import numpy as np
from datasets import Dataset, DatasetDict
from sklearn.model_selection import train_test_split
import torch 
from transformers import AutoTokenizer, Trainer, TrainingArguments, \
    BertForSequenceClassification, DataCollatorWithPadding
from sklearn.metrics import accuracy_score, f1_score

In [76]:
df = pd.read_json("../data/민원(콜센터) 질의응답_다산콜센터_일반행정 문의_Training.json")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50336 entries, 0 to 50335
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   도메인        50336 non-null  str
 1   카테고리       50336 non-null  str
 2   대화셋일련번호    50336 non-null  str
 3   화자         50336 non-null  str
 4   문장번호       50336 non-null  int64
 5   고객의도       50336 non-null  str
 6   상담사의도      50336 non-null  str
 7   QA         50336 non-null  str
 8   고객질문(요청)   50336 non-null  str
 9   상담사질문(요청)  50336 non-null  str
 10  고객답변       50336 non-null  str
 11  상담사답변      50336 non-null  str
 12  개체명        50336 non-null  str
 13  용어사전       50336 non-null  str
 14  지식베이스      50336 non-null  str
dtypes: int64(1), str(14)
memory usage: 13.7 MB

In [77]:
df.rename(
    columns = {
        '도메인' : ' 도메인'
    }, inplace = True
)

In [78]:
df.iloc[18: 30]

,도메인,카테고리,대화셋일련번호,화자,문장번호,고객의도,상담사의도,QA,고객질문(요청),상담사질문(요청),고객답변,상담사답변,개체명,용어사전,지식베이스
18,다산콜센터,일반행정 문의,B2240,고객,19,지방세납부,,Q,다른곳에서는 납부할수 없습니까?,,,,,납부방법/지방세/ 위텍스/ 납부,
19,다산콜센터,일반행정 문의,B2240,상담사,20,,지방세납부,A,,,,이용하시는 은행의 사이트에서도 지방세 납부가 가능합니다.,"은행, 사이트",은행/공공기관,"사이트,공공기관"
20,다산콜센터,일반행정 문의,B2241,고객,1,지방세납부,,Q,지방세는 조회할 수 있습니까?,,,,"지방세, 조회",지방세/세금,"조회,세금"
21,다산콜센터,일반행정 문의,B2241,상담사,2,,지방세납부,A,,,,간단한 본인확인 후 안내해드리겠습니다.,"본인확인, 안내",,안내
22,다산콜센터,일반행정 문의,B2241,고객,3,지방세납부,,A,,,알겠습니다.,,,,
23,다산콜센터,일반행정 문의,B2241,상담사,4,,지방세납부,Q,,지금 전화거신 핸드폰이 본인명의 맞습니까?,,,"핸드폰, 본인명의",핸드폰/전자기기,"본인명의,전자기기"
24,다산콜센터,일반행정 문의,B2241,고객,5,지방세납부,,A,,,맞습니다.,,,,
25,다산콜센터,일반행정 문의,B2241,상담사,6,,지방세납부,Q,,생년월일을 말씀해주시겠습니까?,,,생년월일,생년월일/개인정보,"생년월일,개인정보"
26,다산콜센터,일반행정 문의,B2241,고객,7,지방세납부,,A,,,OO월OO일 입니다.,,,,
27,다산콜센터,일반행정 문의,B2241,상담사,8,,지방세납부,Q,,살고계신 주소는 어디입니까?,,,주소,주소/개인정보,"주소,개인정보"
28,다산콜센터,일반행정 문의,B2241,고객,9,지방세납부,,A,,,서울특별시 00구 00동입니다.,,,,
29,다산콜센터,일반행정 문의,B2241,상담사,10,,지방세납부,Q,,상세주소도 말해주시겠습니까?,,,상세주소,상세주소/개인정보,"상세주소,개인정보"

In [79]:
# 데이터프레임 로드 하고 컬럼의 이름들을 확인! 
df.columns.str.strip()

Index(['도메인', '카테고리', '대화셋일련번호', '화자', '문장번호', '고객의도', '상담사의도', 'QA',
       '고객질문(요청)', '상담사질문(요청)', '고객답변', '상담사답변', '개체명', '용어사전', '지식베이스'],
      dtype='str')

In [80]:
df.columns.map( lambda x : x.strip() )

Index(['도메인', '카테고리', '대화셋일련번호', '화자', '문장번호', '고객의도', '상담사의도', 'QA',
       '고객질문(요청)', '상담사질문(요청)', '고객답변', '상담사답변', '개체명', '용어사전', '지식베이스'],
      dtype='str')

In [81]:
df.columns = [ x.strip() for x in df.columns ]

In [82]:
df.head()

,도메인,카테고리,대화셋일련번호,화자,문장번호,고객의도,상담사의도,QA,고객질문(요청),상담사질문(요청),고객답변,상담사답변,개체명,용어사전,지식베이스
0,다산콜센터,일반행정 문의,B2240,고객,1,지방세납부,,Q,지방세를 내려면 어떻게 해야됩니까?,,,,지방세,지방세/세금,"지방세,세금"
1,다산콜센터,일반행정 문의,B2240,상담사,2,,지방세납부,A,,,,이용하시는 은행의 사이트에서 지방세 납부가 가능합니다.,"은행, 사이트, 지방세, 납부",은행/공공기관/ 지방세/세금,"사이트,세금"
2,다산콜센터,일반행정 문의,B2240,고객,3,지방세납부,,Q,은행 어플에서도 됩니까?,,,,"은행, 어플",은행/공공기관,"어플,공공기관"
3,다산콜센터,일반행정 문의,B2240,상담사,4,,지방세납부,Q,,어떤 은행을 이용하고 계십니까?,,,은행,은행/공공기관,"은행,공공기관"
4,다산콜센터,일반행정 문의,B2240,고객,5,지방세납부,,A,,,기업은행을 이용하고 있습니다.,,기업은행,기업은행/상호,"기업은행,상호"

In [83]:
# 필요한 컬럼을 제외하고 나머지는 제외 
df2 = df[['고객질문(요청)', '상담사답변']]

In [84]:
df2.rename(
    columns = {
        '고객질문(요청)' : '고객질문'
    }, inplace = True
)

In [85]:
# 텍스트 정규화 
def normalize(text):
    text = re.sub(r"[^가-힣0-9a-zA-Z\s\.]", ' ', str(text))
    text = re.sub(r"\s+", ' ', text).strip()

    return text

In [86]:
df2 = df2.map(normalize)

In [87]:
flag1 = (df2['고객질문'] != '') & (df2['상담사답변'].shift(-1) != '') & (df['문장번호'] == 1)
df3 = df2.loc[flag1, ]

In [88]:
# flag1을 한칸씩 밑으로 내리면 상담사의 답변
df3['상담사답변'] = df2.loc[flag1.shift(1).fillna(False), '상담사답변'].tolist()

In [89]:
df3.head()

,고객질문,상담사답변
0,지방세를 내려면 어떻게 해야됩니까,이용하시는 은행의 사이트에서 지방세 납부가 가능합니다.
20,지방세는 조회할 수 있습니까,간단한 본인확인 후 안내해드리겠습니다.
40,서울시주최 페스티벌 예매해놨는데 예정대로 진행됩니까,현재로썬 진행될 예정입니다.
60,청년저축계좌 지금 신청할 수 있습니까,죄송하지만 이미 신청기간이 지났습니다.
200,보건증 무인발급기로 출력할 수 있습니까,보건증은 모든 보건소에서 지원하는게 아니라서 검사받은 보건소 확인이 필요합니다.

In [90]:
df3.info()

<class 'pandas.DataFrame'>
Index: 1087 entries, 0 to 50316
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   고객질문    1087 non-null   str
 1   상담사답변   1087 non-null   str
dtypes: str(2)
memory usage: 149.2 KB

In [91]:
# 기존의 데이터의 질문과 답변은 정상적인 답변 labels를 1로 채워준다. 
df3['labels'] = 1

In [92]:
# 기존의 질문은 유지한채 답변은 바꿔서 labels가 0인 구간을 생성 
answer_list = [
    ['A', 'a'], 
    ['B', 'b'], 
    ['C', 'c'], 
    ['D', 'd']
]
neg_list = []
for q, a in answer_list:
    # q : 질문
    # a : 답변

    cand = []
    for q2, a2 in answer_list:
        # a2 : 답변들의 목록
        if a != a2:
            cand.append(a2)
    # cand 틀린 답변의 목록에서 무작위로 하나를 선택 
    neg_a = np.random.choice(cand)
    neg_list.append([q, neg_a])

neg_list

[['A', np.str_('d')],
 ['B', np.str_('a')],
 ['C', np.str_('d')],
 ['D', np.str_('c')]]

In [93]:
answer_list2 = df3[['고객질문', '상담사답변']].values.tolist()

In [94]:
neg_list2 = []
for q, a in answer_list2:
    cand = [ a2 for q2, a2 in answer_list2 if a != a2 ]

    neg_a = np.random.choice(cand)
    neg_list2.append( [q, neg_a] )
neg_list2

[['지방세를 내려면 어떻게 해야됩니까', np.str_('예 성실히 답변 드리겠습니다.')],
 ['지방세는 조회할 수 있습니까', np.str_('네 건강보험이 적용됩니다.')],
 ['서울시주최 페스티벌 예매해놨는데 예정대로 진행됩니까', np.str_('네 서울도서관을 운영중입니다.')],
 ['청년저축계좌 지금 신청할 수 있습니까', np.str_('예.거주지 근처 주민센터에서 발급 가능하십니다.')],
 ['보건증 무인발급기로 출력할 수 있습니까',
  np.str_('우리동네키움센터는 초등학생 누구나 돌봄을 필요로 할 때 이용할 수 있는 곳입니다.')],
 ['안녕하세요. 제가 이번에 공무원 시험을 봤는데 시험 결과는 언제 나옵니까', np.str_('네 있습니다.')],
 ['농촌일손돕기 봉사 신청하려고합니다.',
  np.str_('취득세란 일정한 자산을 취득했을 때 이에 대해 부과하는 조세를 뜻하는 용어입니다.')],
 ['주말농장 신청하려고 합니다.', np.str_('청년의 다양한 상황과 필요에 맞게 사용이 가능합니다.')],
 ['안녕하세요. 저 장학생 문의하려 합니다.', np.str_('네 무엇이 궁금하신가요')],
 ['안녕하세요. 유기동물 복지 관련 문의드리려합니다.', np.str_('건강보험관리공단에 신청하시면 됩니다.')],
 ['가산도서관 지금 이용 불가입니까', np.str_('물론 접수 가능합니다.')],
 ['농기계 대여 하려합니다.', np.str_('네 합니다')],
 ['서울시민체육센터 지금 운영합니까', np.str_('마라톤처럼 코스를 정해두고 책 읽기 경주하는겁니다.')],
 ['기초수급자 신청하려고 합니다.',
  np.str_('자동차세는 보통 1월에서 6월까지의 자동차세를 6월에 후불 납부하고 7월에서 12월까지의 자동차세를 12월에 후불 납부하고 있습니다.')],
 ['운전면허 갱신하려합니다.', np.str_('결과는 9월 20일로 예정되어있어요.')],
 ['이번에 한국사 시험 미뤄집니까', np.str_('네. 무엇을 도와드릴까요')],
 ['여권재발급 받으려고 하는데요 신규디자인으로 받을 수 있습니까', np.str_('많이 힘드시겠어요..')],
 ['지방세를 내려면 어떻게 해야되요', np.str_('네 건강보험이 적용됩니다.')],
 ['지방세는 조회할 수 있어요', np.str_('네.')],
 ['서울시주최 페스티벌 예매해놨는데 예정대로 진행되나요', np.str_('여가문화 확산을 위해서 소비할인권을 제공하는것입니다.')],
 ['청년저축계좌 지금 신청할 수 있나요', np.str_('신원조회 해드리겠습니다.')],
 ['보건증 무인발급기로 출력할 수 있어요',
  np.str_('2020년 4월 30일 기준으로 이혼소송이 진행중이라면 이의신청을 통해 가구원에게 분리지급 가능합니다')],
 ['안녕하세요. 제가 이번에 공무원 시험을 봤는데 시험 결과는 언제 나와요',
  np.str_('귀농교육은 온 오프라인으로 수강가능하십니다')],
 ['농촌일손돕기 봉사 신청하려는데요.', np.str_('네 대관 가능합니다.')],
 ['주말농장 신청하고싶은데요.', np.str_('네.')],
 ['안녕하세요. 저 장학생 문의하려구요.', np.str_('도로 점용료 사용료율 1 인하해 드립니다')],
 ['안녕하세요. 유기동물 복지 관련 문의하려는데요.', np.str_('네.')],
 ['가산도서관 지금 이용 못하나요', np.str_('아직 신규 디자인 발급은 불가능하십니다.')],
 ['농기계 대여 하려는데요.', np.str_('네 말씀하세요')],
 ['서울시민체육센터 지금 운영하나요', np.str_('네 됩니다')],
 ['기초수급자 신청하려는데요.', np.str_('죄송하지만 이미 신청기간이 끝났어요.')],
 ['운전면허 갱신하려는데요.', np.str_('서울청년포털 공지에서 확인 가능합니다.')],
 ['이번에 한국사 시험 미뤄졌어요', np.str_('관할구청 연락해서 말씀해주셔도 되고 OOO 신고센터에도 신고 가능합니다.')],
 ['여권재발급 받으려고 하는데요 신규디자인으로 받을 수 있어요',
  np.str_('취업을 준비하는 청년들에게 매월 50만원씩 최대 6개월간 구직활동지원금을 지원하는 제도 입니다.')],
 ['지방세 어떻게 내', np.str_('동대문 도서관이 있습니다')],
 ['지방세 조회할 수 있어',
  np.str_('소득 4분위 이하 무주택세대 구성원에게 정부가 직접 건설하거나 매입한 아파트를 공급해주는 제도입니다.')],
 ['서울시주최 페스티벌 예매했는데 예정대로 진행돼', np.str_('네 먼저 신원조회 해드리겠습니다.')],
 ['청년저축계좌 지금 신청할 수 있어', np.str_('네')],
 ['보건증 무인발급기로 출력돼', np.str_('청년월세지원은 청년통장과 중복으로 지원이 됩니다.')],
 ['이번에 공무원 시험을 봤는데 시험 결과는 언제 나와', np.str_('네. 서울시에서 운영하는거라 서울에서만 탑승가능하십니다.')],
 ['농촌일손돕기 봉사 신청할래.', np.str_('네')],
 ['주말농장 신청하고싶어.', np.str_('네 말씀하세요')],
 ['장학생 문의하려구.', np.str_('길고양이를 대상으로 중성화 사업진행 중입니다.')],
 ['유기동물 복지 관련 문의하고싶은데', np.str_('코로나 여파로 올해 행사는 취소되었습니다.')],
 ['가산도서관 지금 이용 못해', np.str_('네 위임장을 작성하셔서 대리방문 접수 가능합니다.')],
 ['농기계 대여 하는거 좀 물어보고싶은데.', np.str_('이용하시는 은행의 사이트에서 지방세 납부가 가능해요.')],
 ['서울시민체육센터 지금 운영해', np.str_('네. 말씀하세요')],
 ['사정이 있어서 아기 출생신고를 못했는데요.', np.str_('예 물음에 성실히 답변드리겠습니다.')],
 ['청소년증 발급받고 싶은데 시청에서 하면 되나요', np.str_('성실히 답변 드리겠습니다.')],
 ['청소년증 사진 여권사진으로 해도 되는거에요', np.str_('네 가능합니다.')],
 ['청소년증 발급하면 교통카드로도 사용할 수 있죠', np.str_('네')],
 ['문화누리카드로 대중교통 이용가능한가요', np.str_('네 설명가능합니다.')],
 ['안녕하세요. 장애인 복지카드로 지하철 무료로 탑승 가능하다고 해서요.', np.str_('예 물음에 성실히 답변 드리겠습니다.')],
 ['아버지가 이번에 만 65세가 되시는데 경로우대 교통카드 받을 수 있나요',
  np.str_('기존에는 직접 방문만 가능했는데 이제는 인터넷으로도 가능하십니다.')],
 ['안녕하세요. 이번에 이사를 가게 되었는데 시니어패스 계속 사용해도 되나요', np.str_('아닙니다.')],
 ['시니어패스 지하철말고 버스에서도 사용가능한가요', np.str_('서울역 옥상 공중보행길이 지난달 개통했습니다')],
 ['청년수당을 받다가 취업을 하면 어떻게하죠', np.str_('성동 금호 용담 무지개 성수 청계도서관이 있습니다.')],
 ['청년수당 신청 가능 대상은 어떻게 되죠', np.str_('책 대여는 가능하신데 자유열람실은 이용 불가에요.')],
 ['청년수당은 카드 사용만 가능한가요', np.str_('네 말씀해주세요.')],
 ['청년수당 모집기간 종료되었나요', np.str_('공원 같은 광화문광장이 내년 10월에 완공 됩니다.')],
 ['실업급여 받는 중인데 청년수당 지원 못하나요', np.str_('예. 그렇습니다.')],
 ['청년수당 신청 서류가 따로 있나요', np.str_('네 있습니다.')],
 ['청년수당에 대한 질문이 많습니다.', np.str_('네 말씀하십시오')],
 ['대학교 제적 상태여도 청년수당 신청 가능한가요', np.str_('어린이 보호 구역에 주차를 하시면 안됩니다.')],
 ['제가 대학교를 안 나왔는데 청년수당 받을 수 있나요', np.str_('개별소비세 교육세 부가가치세가 있습니다.')],
 ['언니랑 제가 둘 다 희망두배 청년통장 신청 가능한가요',
  np.str_('국제운전면허증은 전국 운전면허시험장 및 경찰서에서 발급이 가능합니다.')],
 ['가족관계증명서는 어디서 받을 수 있나요', np.str_('네 말씀하세요')],
 ['희망두배 통장 신청했는데 발표는 언제나나요',
  np.str_('한국환경공단 콜센터1OOO OOOO 자동차배출가스등급제 누리집을 통해서 확인 가능합니다.')],
 ['따릉이라는게 있다는데 이게 자전거에요', np.str_('네 말씀하세요.')],
 ['따릉이 관련 질문이 있습니다.', np.str_('네. 여권상담가능합니다.')],
 ['따릉이 스마트폰으로만 이용가능한거죠', np.str_('네 말씀해주세요.')],
 ['따릉이 누구나 탈 수 있나요', np.str_('네. 말씀하세요.')],
 ['한강에 수상택시가 있다는데 사실인가요', np.str_('교통과로 문의하시면 됩니다.')],
 ['안녕하세요. 한강 수상택시로 관광도 할 수 있다고 해서요.', np.str_('네 최종학력 졸업 후 2년 경과하면 가능합니다.')],
 ['희망두배 청년통장에 대해 물을게 있어서요.', np.str_('중앙마라톤은 올해 취소되었습니다.')],
 ['서울사랑상품권 환불 할 수 있나요', np.str_('주민등록증은 대리인 신청이 불가합니다')],
 ['서울사랑상품권 관련 질문이 있어서요.', np.str_('네 말씀하세요')],
 ['민원 24로 주민등록증 재발급 신청 가능한가요', np.str_('시민의 월세 부담을 줄이기 위한 지원사업입니다.')],
 ['보건증 발급은 주소지 관할 보건소에서만 할 수 있나요',
  np.str_('청년취업과 중소기업을 장려하기 위해 서울시에서 기업에 장려금을 지원하는 사업입니다.')],
 ['서울시 신혼부부 이자지원 받으려면 지금 거주중이면 안되나요',
  np.str_('특별공급 소득요건을 추가 완화해 소득이 많은 맞벌이 신혼 부부들이 수혜를 볼 수 있도록 개정에 착수할 계획입니다.')],
 ['안녕하세요. 노인돌보미는 어디서 신청하죠', np.str_('방문 납부와 온라인 납부가 가능합니다.')],
 ['서울시에서 전기차 지원해준다고 하던데요',
  np.str_('10만원 또는 15만원 통장에 저축하시면 2배가 넘는 금액을 수령가능한 통장입니다.')],
 ['재산세는 국세인가요 지방세 인가요', np.str_('예 성심성의껏 답변해 드리겠습니다.')],
 ['가족관계증명서 무인민원발급기에서 발급가능한가요', np.str_('1365자원봉사포털에서 신청 가능해요.')],
 ['한강공원 축구장 이용할 수 있을까요', np.str_('예 무엇이든지 물어보세요')],
 ['저희가 신혼부부 임차보증금지원을 받았었는데요 대출기간이 안끝났는데 이혼을 하게 되면 어떻게 되나요',
  np.str_('지방소득세는 납세의무를 가지고 있는 개인 법인이 소득에 따라 납부하게 되는 지방세입니다.')],
 ['나이가 많아서 일을 할 수 가 없습니다. 도움을 받을 수 없을까요', np.str_('아닙니다.')],
 ['희망의 집수리 신청은 어떻게 하나요',
  np.str_('네 도시농업은 말 그대로 도시 내에서 농작물 수목 화초를 재배하거나 곤충을 사육하는 것을 말합니다.')],
 ['우리동네키움센터는 어떤곳인가요', np.str_('취득세는 자동차세분 취득세분 주민세분취득세는 자동차세분 등록면허세분 재산세분')],
 ['부동산종합정보를 좀 얻고싶은데 어디서 얻을 수 있나요', np.str_('네 각 주민센터 행정센터에 비치되어 있습니다.')],
 ['시의회에서 하는일은 무엇인가요', np.str_('청년 주거비 부담을 덜어주기위한 월세 지원 사업입니다.')],
 ['지금 예약가능한 전시 프로그램 있나요', np.str_('신청은 1365자원봉사포털에서 가능하십니다.')],
 ['금연구역에 관한 질문 좀 할게요', np.str_('보건증은 보건소에서 발급을 하고 있습니다.')],
 ['안과질환으로 검사를 받고 싶은데 건강보험 적용되나요', np.str_('건강보험관리공단에 신청하시면 됩니다.')],
 ['요새 유튜버들이 광고 표시 안했다고 엄청 시끄럽던데 갑자기 왜 그런거예요', np.str_('네 확인해 드릴게요.')],
 ['전세보증금 반환보증 제도가 뭐예요', np.str_('네 현재 지급이 끝났고 지금은 2차 지원금 신청기간입니다')],
 ['청년 전세임대 입주자 모집한다고 하는데 그게 뭔가요', np.str_('예 성실히 답변 드리겠습니다.')],
 ['청년 전세 임대에 입주하고 싶은데 지금 제가 차상위계층 가구에 해당하는데 1순위 맞나요',
  np.str_('만 65세 이상이시면 되십니다')],
 ['가족돌봄비용을 지원받고 싶은데 가능할까요',
  np.str_('인감증명서는 온라인 발급이 불가능하고 본인이나 대리인이 직접 동사무소에 방문하셔서 발급받으셔야 합니다')],
 ['지금 제가 프리랜서로 일하고 있는데 구직지원금을 또 받을 수 있을까요',
  np.str_('가까운 행정복지센터로 가셔도 되고 인터넷으로 발급이 가능합니다')],
 ['소상공인에게 지원금 준다는데 진짜예요', np.str_('QR형 뉴따릉이로 업그레이드 됩니다.')],
 ['지방세내라고 고지서가 왔는데 지방세가 뭐예요', np.str_('네 가능합니다.')],
 ['취득세가 뭐예요', np.str_('안타깝지만 현재는 종료가 된 상황입니다.')],
 ['아버지가 차를 사주셨는데 오늘 자동차세 고지서가 저한테 왔어요 왜 제가 내야 되죠', np.str_('현재 온라인 시행중입니다.')],
 ['자동차 세금이 좀 줄어든것 같은데요', np.str_('네 있습니다.')],
 ['지방세 납부내역를 알고싶은데요', np.str_('네 재산세는 보유하신 주택이 있으시면 납부하게 됩니다.')],
 ['지방소득세가 뭔지 알고 싶어요.', np.str_('네 상담가능합니다.')],
 ['출산급여 지원 혜택을 받고 싶은데 받을 수 있을까 문의 드립니다.', np.str_('네. 그렇습니다.')],
 ['아파트에 살고 있는데 윗 집이 너무 시끄러워서 짜증나요. 어떻게 해야 되요',
  np.str_('문의 하신 사항에 답을 해 드리겠습니다.')],
 ['층간소음이웃센터라는 곳이 있어요', np.str_('네 합니다')],
 ['증여세 신고기한 알고 싶어요.',
  np.str_('지방세는 해당 시 군 내에 주소를 두고 있는 개인세대주 사업소를 둔 개인사업자 법인에게 부과세는 세금입니다.')],
 ['연말정산 언제하는 거예요', np.str_('예 물음에 성의껏 답변 드리게습니다.')],
 ['취업 후 학자금 상환제도라는게 있나요', np.str_('네. 서울시에서 운영하는거라 서울에서만 탑승가능하십니다.')],
 ['국가장학금 유형이 있어요', np.str_('예 여쭤보신사항에 성실히 답변 드리겠습니다.')],
 ['한국장학재단에 기부하고 싶은데 방법 좀 알려주세요.',
  np.str_('임대인이 임차인에게 반환하는 전세보증금의 반환을 책임지는 보증상품입니다.')],
 ['어린이 보호 구역에 주차가 가능 한가요', np.str_('네. 이의신청 가능하십니다.')],
 ['요새 전동킥보드를 타고 다니는 사람들이 많은데 너무 위험한 같아요. 관련 법이 있나요', np.str_('네 가능합니다.')],
 ['주민등록초본을 발급 받고 싶은데 어디서 발급받죠',
  np.str_('네 각 구청에서 동물보호센터를 지정하여 동물들을 구조하고 보호하고 있습니다.')],
 ['자동차를 샀는데 취득세를 내야하나요', np.str_('네. 직접 방문하시거나 온라인으로 신고하실 수 있습니다.')],
 ['청년수당 신청 어디서 할까요', np.str_('네 서울시 행복주택사업이라는게 있습니다.')],
 ['서울시에서 하는 지역일자리 사업이 있나요', np.str_('네 확인해보겠습니다.')],
 ['우리소리박물관이라고 있나요', np.str_('궁금하신것 알려드리겠습니다')],
 ['안과질환으로 검사를 받고 싶은데 건강보험 적용되나요', np.str_('네 있습니다')],
 ['요새 유튜버들이 광고 표시 안했다고 엄청 시끄럽던데 갑자기 왜 그런거예요', np.str_('네 먼저 신원조회 해드리겠습니다.')],
 ['전세보증금 반환보증 제도가 뭐예요', np.str_('예 성실히 답변 드리겠습니다.')],
 ['청년 전세임대 입주자 모집한다고 하는데 그게 뭔가요', np.str_('네 됩니다')],
 ['청년 전세 임대에 입주하고 싶은데 지금 제가 차상위계층 가구에 해당하는데 1순위 맞나요', np.str_('네. 문의해 주세요.')],
 ['가족돌봄비용을 지원받고 싶은데 가능할까요', np.str_('예 무엇이든지 물어보세요')],
 ['지금 제가 프리랜서로 일하고 있는데 구직지원금을 또 받을 수 있을까요', np.str_('네 합니다.')],
 ['소상공인에게 지원금 준다는데 진짜예요',
  np.str_('갑작스러운 위기 사유의 발생으로 생계유지가 곤란한 저소득 위기가구에 대히 생계비 등을 신속하게 제공하여 안정적 생활을 유지하도록 지원하는 제도입니다')],
 ['지방세내라고 고지서가 왔는데 지방세가 뭐예요', np.str_('네 끝났습니다')],
 ['취득세가 뭐예요', np.str_('관할구청 연락해서 말씀해주셔도 되고 120 신고센터에도 신고하시면 됩니다.')],
 ['아버지가 차를 사주셨는데 오늘 자동차세 고지서가 저한테 왔어요 왜 제가 내야 되죠',
  np.str_('연매출 2억 이하 6개월 이상 업력의 소상공인을 대상으로 지원하는 정책입니다.')],
 ['자동차 세금이 좀 줄어든것 같은데요',
  np.str_('보건증은 보건소에서 발급 받으나 현재 코로나 19로 인해 업무를 안하는 곳이 많아 관할 보건소에 먼저 문의를 해보시는 게 좋습니다')],
 ['지방세 납부내역를 알고싶은데요', np.str_('네 무엇이 궁금하신가요')],
 ['지방소득세가 뭔지 알고 싶어요.', np.str_('네')],
 ['출산급여 지원 혜택을 받고 싶은데 받을 수 있을까 문의 드립니다.', np.str_('네')],
 ['아파트에 살고 있는데 윗 집이 너무 시끄러워서 짜증나요. 어떻게 해야 되요', np.str_('네.')],
 ['층간소음이웃센터라는 곳이 있어요', np.str_('교통불편신고 접수 가능하십니다.')],
 ['증여세 신고기한 알고 싶어요.', np.str_('네')],
 ['연말정산 언제하는 거예요', np.str_('네 긴급재난지원금 지금 기준은 주민등록표의 세대를 기준으로 산정이 되었습니다')],
 ['취업 후 학자금 상환제도라는게 있나요', np.str_('네 1유형과 2유형으로 나뉩니다.')],
 ['국가장학금 유형이 있어요', np.str_('간단한 본인확인 후 안내해드리겠습니다.')],
 ['한국장학재단에 기부하고 싶은데 방법 좀 알려주세요.', np.str_('네 11월 27일 개관을 합니다')],
 ['어린이 보호 구역에 주차가 가능 한가요', np.str_('네 신고하실 수 있습니다.')],
 ['요새 전동킥보드를 타고 다니는 사람들이 많은데 너무 위험한 같아요. 관련 법이 있나요', np.str_('반려동물 행사가 있습니다')],
 ['주민등록초본을 발급 받고 싶은데 어디서 발급받죠', np.str_('물론 접수 가능합니다.')],
 ['경력 단절 주부인데요 다시 일을하고싶은데 서울시에서 저같은 주부들을 도와주는 프로그램이 있다고 들어서 문의합니다',
  np.str_('취득일로부터 60일 이내에 신고 납부해야 합니다.')],
 ['서울형 뉴딜일자리 정책 대상이 궁금합니다', np.str_('물음에 성실히 답변 드리겠습니다.')],
 ['서울역사박물관 재개관 했나요 거리두기 때문에 휴관했다고 알고있는데', np.str_('네. 무엇을 도와드릴까요')],
 ['강남구에 도서관이 있나요', np.str_('네 말씀하세요.')],
 ['서울대공원 갈건데요 코끼리열차랑 리프트 같이 이용하면 좀 할인 되나요', np.str_('네 말씀하세요.')],
 ['서울대공원에 치유의숲이라는데가 있다던데 어떤곳인가요', np.str_('네 건강보험이 적용됩니다.')],
 ['서울식물원 열었나요', np.str_('네 설명가능합니다.')],
 ['저 올해 하반기에 뉴질랜드로 워킹홀리데이 가려고 했는데 지금 못가나요', np.str_('그렇지 않습니다.')],
 ['졸업증명서를 좀 받고싶은데요.', np.str_('임산부에게 친환경농산물 꾸러미를 지급하는 사업입니다.')],
 ['재학증명서를 좀 받고싶은데요.', np.str_('취득일로부터 60일 이내에 신고 납부해야 합니다.')],
 ['유상취득세 감면사유가 있을 경우 위택스에서 신고 가능한가요', np.str_('네')],
 ['토지 및 건물에 대한 무상취득세 신고 가능한가요', np.str_('가능한 곳도 있고 아닌곳도 있습니다.')],
 ['지방세 대리신청제도가 생겼다고 하는데 어디에 문의를 하면 되나요',
  np.str_('취득세는 담배소비세분 자동차세분 레저세분취득세는 등록면허세분 재산세분 담배소비세분 이 있습니다.')],
 ['지금 도서관 이용가능한가요', np.str_('네 동물 등록을 반드시 해 주셔야 합니다.')],
 ['여권 분실시 어떤 불이익이 있나요',
  np.str_('먼저 회원가입 여부에 상관없이 기부하실 수 있으신데 편하신 납부 방법을 선택하셔서 입금하시면 됩니다.')],
 ['개명신청하려고 하는데 법원 방문해야하나요',
  np.str_('보건증은 보건소에서 발급을 하나 현재 코로나 19때문에 보건증 업무를 한국건강관리협회나 기타 보건기관에 위탁하기도 합니다')],
 ['아빠가 저 호적에서 판다고 하는데 진짜 뭐 가능한 일인가요', np.str_('네 말씀하세요.')],
 ['주민등록증 발급 기간이 어떻게 되나요',
  np.str_('서울에는 없고 경기도 양평과 광주 등에 함께 서울 친환경농장 가꾸기 관련 시설이 있습니다.')],
 ['주민등록증 발급하려고 하는데요 사진 문의좀 할게요.', np.str_('네')],
 ['안녕하세요. 제가 버스에 카메라를 두고 내린거같은데 찾을 수 있을까요',
  np.str_('한국환경공단 콜센터1OOO OOOO 자동차배출가스등급제 누리집을 통해서 확인 가능합니다.')],
 ['불법주차 차량 어디에 신고해야 하나요', np.str_('네')],
 ['귀농귀촌교육을 어디서 받을 수 있나요', np.str_('네 말씀하십시요.')],
 ['귀농귀촌 정책지원 사업신청은 어떻게 해야하나요', np.str_('동주민센터나 온라인에서 발급 받으실 수 있습니다.')],
 ['청년 대상 농업인 정책이 뭐가 있나요', np.str_('네 소상공인에게 새희망자금을 지원할 계획입니다.')],
 ['현재 중소기업에서 근무중인데 청년내일채움공제 가입할 수 있나요', np.str_('예.거주지 근처 주민센터에서 발급 가능하십니다.')],
 ['주민등록표등본은 무료인가요',
  np.str_('취득세는 주민세분 레저세분 취득세분취득세는 취득세분 자동차세분 주민세분 이있있겠습니다.')],
 ['민원24 이용하려면 로그인 해야하나요', np.str_('네 담당자분으로 연결도와드릴게요.')],
 ['요즘 길고양이들이 너무 울어대서 미치겠어요 무슨 대책 없나요', np.str_('네 현재 운영중입니다')],
 ['청년 구직 지원금 신청기간인가요', np.str_('층간 소음이 문제이신구요.')],
 ['청년 구직지원금 문의하고 싶은데요', np.str_('네 진행되고 있습니다')],
 ['수고하십니다. 청년구직 지원금 문의하고싶은데요', np.str_('아 그러시군요. 운영센터를 안내해드리겠습니다.')],
 ['고용보험 실업급여 질문 드리고 싶습니다.', np.str_('네 패키지 요금으로 이용하시면 할인 가능합니다')],
 ['미국국적민인데요. 청년사회서비스 신청문의할 수 있나요', np.str_('종료되었슴니다.')],
 ['올해 희망두배 청년통장모집은 마감됐나요',
  np.str_('먼저 회원가입 여부에 상관없이 기부하실 수 있으신데 편하신 납부 방법을 선택하셔서 입금하시면 됩니다.')],
 ['내년에 희망두배 청년통장 신청하려고 하는데요', np.str_('예 말씀하세요')],
 ['희망두배 발표 났나요', np.str_('네 맞습니다')],
 ['내일채움공제 좀 알아보려고 하는데요', np.str_('궁금한 사항을 여쭤봐 주세요')],
 ['근로장려금 좀 알아보려고 하는데요', np.str_('네 매년 불꽃놀이축제를 합니다')],
 ['서울따릉이 이용 문의하고 싶은데요', np.str_('간단한 본인확인 후 안내해드리겠습니다.')],
 ['학교앞 등교길에 공사차량이 위험한데요.', np.str_('네')],
 ['자동차세 문의 좀 하려구요.', np.str_('주민센터 혹은 인터넷 발급 가능합니다.')],
 ['안녕하세요.', np.str_('매주 월요일과 공휴일은 휴관일입니다.')],
 ['대전에 시립미술관이 있나요',
  np.str_('청년을 대상으로 일정기간 일정금액을 저축하면 저축액의 2배이상을 받을수 있는 통장입니다.')],
 ['시립미술관 대관 하려고 하는데 가능한가요', np.str_('예 성실히 답변 드리겠습니다.')],
 ['올해도 애완곤충 경진대회 해요', np.str_('네 말씀하십시오.')],
 ['안녕하세요.', np.str_('교통과로 문의하시면 됩니다.')],
 ['안녕하세요.', np.str_('만65세이상부터 수급자격이됩니다.')],
 ['문의 좀 하려구요.', np.str_('여성일자리 박람회가 OO 월 OO 일에 있네요.')],
 ['안녕하세요.', np.str_('네 패키지 요금으로 이용하시면 할인 가능합니다')],
 ['문의 좀 하려구요.', np.str_('상실신고를 하셔야 합니다.')],
 ['세종 도서관 이용 하려고 하는데요', np.str_('네 말씀하세요')],
 ['행정복지센터도 대관이 가능한가요', np.str_('네 안녕하세요.')],
 ['안녕하세요.', np.str_('확인해드리겠습니다.')],
 ['경기도에서 진행하고 있는 청년수당에 대해서 여쭤보려고요.',
  np.str_('청년들에게 꼭 필요한 정책을 만드는데에 도움이 되는 인재들을 모으는 제도입니다.')],
 ['청년수당은 현급으로 주나요', np.str_('네 조회해 드리겠습니다.')],
 ['다산시에 보건소가 한 개인가요', np.str_('네 확인해 드릴게요.')],
 ['여기에 물어봐도 되는지 모르겠는데요.',
  np.str_('지방자치단체 세무부서나 납세자보호관에 문의하시면 정확한 정보를 얻으실 수 있습니다.')],
 ['음식점에서 일할때 보건증이 다 필요한 건가요',
  np.str_('가까운 동주민센터 방문하시어 자격 해당여부 확인받으신 후 신청서 개인정보제공동의서 등을 작성해주시면 되시겠습니다')],
 ['금연클리닉 가려고 하는데요', np.str_('네')],
 ['제가 지금동 뉴타운 4거리에서 속도위반을 했어요.', np.str_('네 현재 운영중입니다')],
 ['혼인신고 관련해서 질문이 있어요.', np.str_('아직 결정이 않됐는데요')],
 ['아파트 주자창에 장애인 주차구역이 정해져 있잖아요', np.str_('주민센터에서 하실 수 있으십니다.')],
 ['장애인 주차구역에서 주차를 방해하는 행동도 과태료 대상인가요', np.str_('네 도서관 재개관하여 운영중에 있습니다.')],
 ['청년수당이랑 다른가요', np.str_('청년의 저축금액 100 를 추가 적립해 주는 사업입니다.')],
 ['노령연금은 언제부터 받을 수 있는거죠', np.str_('올해 7월부터 시범적으로 시행하고 있습니다.')],
 ['경기도 청년 노동자 통장이란게 있나요', np.str_('책 대여는 가능하신데 자유열람실은 이용 불가에요.')],
 ['주민등록등본이 필요한데 어디서 발급받나요', np.str_('서울시 청년지원사업의 하나입니다.')],
 ['문의좀 드릴께요', np.str_('네 있습니다')],
 ['호털 취소건때문에 문의드립니다', np.str_('위텍스 홈페이지나 모바일앱을 이용해서 조회하실수 있습니다.')],
 ['한부모가정자격 조건에 대해 궁금한게 있어서요', np.str_('네')],
 ['제가 지금 이혼한지 얼마 안됐어요', np.str_('네.')],
 ['지방세를 납부하려구 하는데 궁금한게 있어요', np.str_('네')],
 ['소형 가전도 폐기물 딱지 붙여야 되나요', np.str_('매주 월요일과 공휴일은 휴관일입니다.')],
 ['등본 발급 받으려고 하는데요 집에서 되나요', np.str_('예 궁금한 사항을 여쭤봐 주세요')],
 ['횡단보도에 누가 주차해놨는데 신고가능한가요',
  np.str_('네 각 구청에서 동물보호센터를 지정하여 동물들을 구조하고 보호하고 있습니다.')],
 ['전세계약했는데 확정일자 받아야 되는거죠', np.str_('죄송하지만 이미 신청기간이 지났어요.')],
 ['전세계약 갱신 관련해서 문의 드려요', np.str_('주민센터에서 하실 수 있습니다.')],
 ['서울시에서 출산하면 받을 수 있는 선물이 있다고 하던데요',
  np.str_('네. 서울시에서 운영하는거라 서울에서만 탑승가능하십니다.')],
 ['제로페이가 뭔지 설명좀 부탁드릴께요', np.str_('네.그런데 환급을 받으신후 주택임대 사업자로 변경해야 합니다.')],
 ['신혼부부 특별공급 소득금액 기준이이 현실적으로 너무 한것 같은데요', np.str_('네 담당자분으로 연결해 드릴게요.')],
 ['국립항공박물관이 오픈했다던데 갈수 있나요',
  np.str_('서울시 자치구별로 지역사회 소상공인매출 증대와 지역경제 활성화를 위해 발행한 서울사랑상품권입니다.')],
 ['용산구에 있는 박물관관련 문의 드립니다.', np.str_('청년의 저축금액 100 를 추가 적립해 주는 사업입니다.')],
 ['성동구에 있는 도서관 알려주세요.', np.str_('네 맞습니다. 다산 콜센터입니다.')],
 ['지금 보건소에서 보건증 뗄 수 있나요', np.str_('어린이 보호 구역에 주차를 하시면 안됩니다.')],
 ['희망두배 청년통장 궁금합니다.', np.str_('주민센터에서 하실 수 있으십니다.')],
 ['미혼일 때 아이를 낳으면 출생신고 할 수 있을까요', np.str_('네 말씀해주세요.')],
 ['출생신고 늦게하면 벌금이 있어요', np.str_('QR형 뉴따릉이로 업그레이드 됩니다.')],
 ['청소년증 충전은 모든 편의점에서 가능해요', np.str_('책 대여는 가능하신데 자유열람실은 이용 불가에요.')],
 ['청소년증 어디서 받아요', np.str_('네 말씀하세요')],
 ['청소년증 본인만 발급 가능해요', np.str_('네. 이의신청 기한 내에 이의신청 가능하십니다.')],
 ['청소년증 교통카드로 써도 되는거에요', np.str_('서울시에 거주하는 미취업 청년들의 구직활동을 촉진하는 수당입니다.')],
 ['경로우대 교통카드 자격이 어떻게 되나요', np.str_('아직 신규 디자인 발급은 불가능하십니다.')],
 ['시니어패스 분실 시 어떻게하나요', np.str_('현재 위택스에서는 임대주택감면에 대해서만 신고할 수 있습니다.')],
 ['청년수당 대상자 기준 알고 싶습니다.', np.str_('네 공연명은 클래식OOOO OOOO해피클래식입니다.')],
 ['독감 무료 예방접종 때문에 전화했는데요', np.str_('보건소나 혹은 의료기관에 가셔서 접수하시면 됩니다.')],
 ['가스관련 문의하려는데요', np.str_('네 확인해드리겠습니다.')],
 ['불법주차신고도 여기다 하면 되나요', np.str_('네 서울시 행복주택사업이라는게 있습니다.')],
 ['불법주차 신고하는 덴가요', np.str_('개별소비세 교육세 부가가치세가 있습니다.')],
 ['불법주정차 신고하는 덴가요', np.str_('전자고지를 신청하셔서 자동납부청구서를 이메일로 받으시면 할인 받으실 수 있습니다.')],
 ['건강보험료때문에 전화했는데요.', np.str_('네 상속세 어떤 부분이 궁금하십니까')],
 ['보험 가입때문에 전화했는데요.', np.str_('네 지난 10월 23일 선정자 발표가 되었습니다.')],
 ['네 보험 가입궁금한데요.', np.str_('네 말씀하세요')],
 ['재산세 납입때문에 전화했는데요.', np.str_('서울지역 5인미만 소상공인 사업체 무급휴직자가 대상이 됩니다')],
 ['부가가치세 납입이 궁금한데요',
  np.str_('서울시는 집과 학교에서 도보 10분거리에 우리동네키움센터를 통해 초등돌봄 사업을 하고 있습니다')],
 ['증여세관해 문의할 수 있을까요', np.str_('네 대관 가능합니다.')],
 ['상속세관련 궁금한데요.', np.str_('네 안녕하세요.')],
 ['자동차세관련 궁금한데요.',
  np.str_('지방세 구제 제도는 심사청구제도 과세전 적부심사제도 감사원 심사청주세도 이의신정제도로 이루어져 있습니다.')],
 ['속도위반으로 지로가 날라와서요.', np.str_('취득세는 주민세분 취득세분 재산세분취득세는 취득세분 담배소비세분 재산세분')],
 ['차량 등록에 대해서 알고 싶습니다.', np.str_('네 확인해드리겠습니다.')],
 ['서울청년인재는 뭔가요', np.str_('이용하시는 은행의 사이트에서 지방세 납부가 가능하세요.')],
 ['이사 시기가 불일치해서 보증금을 돌려받지 못하고 있는데 어떻게하면 좋을까요', np.str_('네 가능합니다.')],
 ['취업성공패키지에대해 알려주세요.',
  np.str_('서울시 거주하는 만19세 34세 미취업 청년들의 구직활동을 촉진하는 수당을 지급하는 제도입니다.')],
 ['안녕하세요', np.str_('네')],
 ['서울 밤도깨비야시장에대해 알려주세요.', np.str_('서울시에서는 미세먼지 저감조치로 노후 경유차의 운헹제한제를 실시합니다')],
 ['안녕하세요', np.str_('지방소득세는 납세의무를 가지고 있는 개인 법인이 소득에 따라 납부하게 되는 지방세입니다.')],
 ['희망풍차 긴급 지원 프로그램이 뭔가요', np.str_('발급 시 신청하셔야 됩니다.')],
 ['청년수당 모집해요', np.str_('네 코로나로 인해 뉴질랜드 워홀 비자 신청을 당분간 중지하고 있습니다.')],
 ['실업급여랑 청년수당 같이 못받는건가요', np.str_('소득하위 70 이하 1 400만 가구에 해당되면 받으실 수 있습니다.')],
 ['청년수당은 어디 은행에서 받을 수 잇나요',
  np.str_('서울농부포털 회원가입을 통해 도시농업 활동 정보를 공유하며 그 활동의 확장과 발전을 하고자하는 서울농부를 말합니다.')],
 ['청년수당은 어디에 써야해요', np.str_('네 맞습니다.')],
 ['가족관계증명서를 받고 싶어요. 어떻게 받아요', np.str_('선착순 예약신청하실수 있습니다.')],
 ['희망두배 청년통장 발표 언제나요', np.str_('네 그렇습니다.')],
 ['따릉이 1시간 구매권을 샀는데 30분 탓어요.', np.str_('중앙마라톤은 올해 취소되었습니다.')],
 ['성동구에 갈 수 있는 도서관이 있을까요', np.str_('길고양이를 대상으로 중성화 사업진행 중입니다.')],
 ['지방세는 무엇인가요', np.str_('서울시 청년지원 사업입니다')],
 ['안녕하세요 문의드릴께 있는데요.', np.str_('민원을 넣으시면 확인 후 보수작업이 이뤄집니다.')],
 ['문의드릴께 있는데요.', np.str_('네 말씀하세요')],
 ['부산시에서 무료로 이용할수 있는 애견놀이터가 있나요', np.str_('가맹점에서 하실 수 있어요')],
 ['서울 청년월세지원사업이 뭔가요', np.str_('간단한 본인확인부터 할게요.')],
 ['청년수당이 뭔가요', np.str_('네 현재 지급이 끝났고 지금은 2차 지원금 신청기간입니다')],
 ['독서 마라톤이 뭔가요', np.str_('현재로썬 진행될 예정이에요.')],
 ['희망도서 바로대출은 뭔가요', np.str_('네 그렇습니다')],
 ['제로페이가 뭔가요', np.str_('네 조회해 드리겠습니다.')],
 ['자동차 구입시 내야하는 세금은 뭐가 있어요', np.str_('무인 택배보관서비스입니다.')],
 ['분양받은 아파트는 취득세를 언제까지 내야하나요', np.str_('네 건강검진을 받으실 수 있습니다')],
 ['지방세 납부내역은 어디에서 알수 있나요', np.str_('서울부동산정보광장 웹사이트에서 정보를 얻으시면 됩니다')],
 ['취득세란 뭔가요', np.str_('네.')],
 ['담배소비세라는게 뭔가요', np.str_('네 서울시 행복주택사업이라는게 있습니다.')],
 ['서울시 자전거 대여에 대해서 궁금한데 여기 전화하면 되는 것이 맞나요', np.str_('예 성실히 답변 드리겠습니다.')],
 ['서울시 출산축하선물 주는 것이 있다고 하던데요. 알고 싶습니다.', np.str_('동에서 하는 행사가 있습니다')],
 ['제로페이가 무엇입니까', np.str_('네 신청하시면 가능합니다.')],
 ['서울시 청년 수당이라는게 있던데 뭡니까', np.str_('현재는 신청기간이 마감되었습니다.')],
 ['신혼부부 특별공급대상 조건이 완화되었다던데 무엇입니까', np.str_('네 재개관 했습니다')],
 ['지금 국립중앙박물관 관람 가능한합니까',
  np.str_('소득 4분위 이하 무주택세대 구성원에게 정부가 직접 건설하거나 매입한 아파트를 공급해주는 제도입니다.')],
 ['용산에 가볼 만한 박물관 있습니까',
  np.str_('보건증은 모든 보건소에서 지원하는게 아니라서 검사받은 보건소 확인이 필요합니다.')],
 ['지금 경북궁 야간관람 가능합니까', np.str_('국립중앙박물관 국립한글박물관 전쟁박물관 등이 있습니다.')],
 ['자동차 범칙금이 나왔는데 이의신청이 가능합니까', np.str_('네 있습니다')],
 ['과태료가 나왔는데 이의신청이 가능합니까', np.str_('네 안녕하세요.')],
 ['친환경농산물 꾸러미가 뭡니까', np.str_('위텍스 홈페이지나 모바일앱을 이용해서 조회하실수 있습니다.')],
 ['학자금대출이자지원이 있다던데 맞습니까', np.str_('예 질문에 성실히 답변 드리겠습니다.')],
 ['희망두배청년통장이 뭡니까', np.str_('네.')],
 ['희망두배청년통장 지원 받고 싶은데요.',
  np.str_('인감보호 신청은 본인의 인감을 보호해달라는 특별한 의사의 표시로 본인 또는 본인이 지정한 사람만 본인의 인감증명서를 발급받을 수 있도록 사전에 제한을 요청하는 것입니다')],
 ['안전속도 5030사업이 뭐죠',
  np.str_('지방세 구제 제도는 감사원 심사청주세도 심사청구제도 과세전 적부심사제도 이의신정제도로 이루어져 있겠습니다.')],
 ['청소년교통비 지원사업을 한다는데 어떤건가요', np.str_('종료되었슴니다.')],
 ['본인 명의의 지역화폐카드가 없는경우는 어떻게 하나요', np.str_('개별소비세 교육세 부가가치세가 있습니다.')],
 ['기초생활수급자등도 청소년교통비를 받을수 있나요', np.str_('예 성심 성의껏 답변 드리겠습니다.')],
 ['안녕하세요. 청소년교통비지원사업에 궁금한게 있어서요',
  np.str_('보건증은 모든 보건소에서 지원하는게 아니라서 검사받은 보건소 확인이 필요합니다.')],
 ['지금 국립중앙박물관 관람 가능한가요', np.str_('청년월세지원은 청년통장과 중복으로 지원이 됩니다.')],
 ['용산에서 가볼 수 있는 박물관은 어떤것이 있나요',
  np.str_('확인 결과 행정안정부와 경찰청이 전동킥보드와 관련된 개정 법류를 공포하였고 이 법률은 2020년 12월 10일로 시행됩니다.')],
 ['지방세를 내려는데 어디에 납부해야 하나요',
  np.str_('취득세는 주민세분 취득세분 재산세분취득세는 취득세분 담배소비세분 재산세분')],
 ['비닐과 투명페트병을 별도로 배출해야 하나요', np.str_('네')],
 ['안녕하십니까 분리배출에 대해 여쭤보려는데요', np.str_('일부 강좌만 제한인원으로 운영해요.')],
 ['지방세이의신청을 할 수 있는 신청인의 자격이 무엇인가요', np.str_('확인해드리겠습니다.')],
 ['상속세 관련하여 문의드리고 싶습니다', np.str_('네 먼저 신원조회 해드리겠습니다.')],
 ['서울시 출산축하선물 주는 것이 있다고 하던데요.', np.str_('네 매년 불꽃놀이축제를 합니다')],

In [95]:
neg_df = pd.DataFrame(neg_list2, columns = ['고객질문', '상담사답변'])
neg_df['labels'] = 0
neg_df.head()

,고객질문,상담사답변,labels
0,지방세를 내려면 어떻게 해야됩니까,예 성실히 답변 드리겠습니다.,0
1,지방세는 조회할 수 있습니까,네 건강보험이 적용됩니다.,0
2,서울시주최 페스티벌 예매해놨는데 예정대로 진행됩니까,네 서울도서관을 운영중입니다.,0
3,청년저축계좌 지금 신청할 수 있습니까,예.거주지 근처 주민센터에서 발급 가능하십니다.,0
4,보건증 무인발급기로 출력할 수 있습니까,우리동네키움센터는 초등학생 누구나 돌봄을 필요로 할 때 이용할 수 있는 곳입니다.,0

In [96]:
# df3와 neg_df을 단순 행 결합 
dataset_df = pd.concat(
    [df3, neg_df], axis = 0, ignore_index=True
)

In [97]:
dataset_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2174 entries, 0 to 2173
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   고객질문    2174 non-null   str
 1   상담사답변   2174 non-null   str
 2   labels  2174 non-null   int64
dtypes: int64(1), str(2)
memory usage: 297.1 KB

In [98]:
dataset_df['labels'].value_counts()

labels
1    1087
0    1087
Name: count, dtype: int64

In [99]:
train_df, test_df = train_test_split(
    dataset_df, test_size = 0.5, random_state=42, stratify= dataset_df['labels']
)

In [100]:
train_ds = Dataset.from_pandas(train_df.reset_index(drop=True))
test_ds = Dataset.from_pandas(test_df.reset_index(drop=True))
# DatasetDict
ds = DatasetDict(
    {
        'train' : train_ds, 
        'validation' : test_ds
    }
)

In [101]:
ds

DatasetDict({
    train: Dataset({
        features: ['고객질문', '상담사답변', 'labels'],
        num_rows: 1087
    })
    validation: Dataset({
        features: ['고객질문', '상담사답변', 'labels'],
        num_rows: 1087
    })
})

In [102]:
MODEL_NAME = 'beomi/kcbert-base'
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast = False)
max_len = 128

def token_fn(batch):
    # batch -> dict{'고객질문', '상담사답변'}
    tok = tokenizer(
        batch['고객질문'], 
        batch['상담사답변'], 
        truncation = True, 
        max_length = max_len
    )

    # 토큰화된 데이터에서 token_type_ids는 kobert 모델에서는 사용하지 않는다. 
    # 해당 키를 제거 
    tok.pop("token_type_ids", None)
    return tok

# remove_columns 매개변수 -> 토큰화를 하고 제외시킬 컬럼을 지정 
tok_ds = ds.map(
    token_fn, 
    batched = True, 
    remove_columns = [col for col in dataset_df.columns if col not in ['labels']], 
    # 캐시 사용 안함 
    load_from_cache_file = False
)

Map: 100%|██████████| 1087/1087 [00:00<00:00, 34682.66 examples/s]
Map: 100%|██████████| 1087/1087 [00:00<00:00, 47586.43 examples/s]

In [103]:
tok_ds['train'][0]['input_ids']

[2,
 29896,
 599,
 4307,
 8431,
 9554,
 8518,
 4040,
 17,
 3,
 8270,
 9656,
 24,
 4118,
 28169,
 17024,
 9569,
 4230,
 1410,
 4334,
 4984,
 4715,
 8102,
 16533,
 10009,
 3]

In [104]:
# 배치마다 동적으로 padding 토큰을 추가 
collator = DataCollatorWithPadding(
    tokenizer= tokenizer
)

In [105]:
# 학습 모델 정의 
# BertModel -> dropout -> Linear
model = BertForSequenceClassification.from_pretrained(MODEL_NAME, num_labels = 2)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 7628.45it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: beomi/kcbert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [106]:
# 평가 함수 
def metrics(eval_pred):
    logits, y = eval_pred
    pred = np.argmax(logits, axis = -1)
    return {
        'accuracy_score' : accuracy_score(pred, y), 
        'f1_score' : f1_score(pred, y)
    }

In [107]:
args = TrainingArguments(
    output_dir= './model2', 
    eval_strategy='epoch', 
    save_strategy='epoch', 
    learning_rate=5e-05, 
    weight_decay=0.01, 
    warmup_steps=0.1, 
    num_train_epochs=3, 
    load_best_model_at_end=True, 
    metric_for_best_model='f1_score', 
    greater_is_better=True
)

In [108]:
trainer = Trainer(
    model = model, 
    args = args, 
    train_dataset= tok_ds['train'], 
    eval_dataset= tok_ds['validation'], 
    processing_class= tokenizer, 
    data_collator= collator, 
    compute_metrics= metrics
)

In [109]:
trainer.train()

c:\Users\ekfla\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.04it/s]
c:\Users\ekfla\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.05it/s]
c:\Users\ekfla\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.16it/s]

TrainOutput(global_step=408, training_loss=0.6393448324764476, metrics={'train_runtime': 478.2671, 'train_samples_per_second': 6.818, 'train_steps_per_second': 0.853, 'total_flos': 62037167410380.0, 'train_loss': 0.6393448324764476, 'epoch': 3.0})

In [110]:
['A'] * 3
# ['A'] + ['A'] + ['A']

['A', 'A', 'A']

In [111]:
# 질문과 답변의 목록들이 입력되었을때 가장 올바른 답변을 찾아주는 함수를 하나 생성 
def score_pairs(question, answers):
    # question : 질문
    # answers : 후보 답변들 
    # 질문은 하나고 답변은 여러개 -> 질문과 답변을 1:1 매칭
    questions = [question] * len(answers)
    tokens = tokenizer(
        questions, 
        answers, 
        truncation = True, 
        max_length = max_len, 
        padding = True, 
        return_tensors = 'pt'
    )
    # token_type_ids 제거 
    tokens.pop('token_type_ids', None)

    # 인코딩 데이터를 딕셔너리 형으로 변환 
    inputs = {
        k : v for k, v in tokens.items()
    }

    model.eval()
    with torch.no_grad():
        logits = model(**inputs)['logits']
        probs = torch.softmax(logits, dim = -1)[:, 1]
        # probs -> 1의 확률 -> 정상적인 답변일 확률
    return probs.tolist()

In [112]:
question = "지방세 납부는 어디서 할 수 있나요?"
answers = [
    '이용하시는 은행 사이트나 앱에서 지방세 납부가 가능합니다', 
    '동물 등록은 거주지 구청에서 처리하셔야 합니다', 
    '출입국 관련 업무는 외교부에서 담당합니다'
]

In [113]:
scores = score_pairs(question, answers)

In [114]:
scores

[0.8732510209083557, 0.22710923850536346, 0.22161811590194702]

In [115]:
# 최대값 -> max()
# 최대값의 위치 -> argmax()
# torch.argmax(torch.tensor(scores))
best_idx = np.argmax(scores)

for idx, (answer, score) in enumerate( zip(answers, scores) ):
    # idx : 위치값
    # answer : 답변
    # scores : 1인 확률
    print(f"{idx} : {answer} -> 적합 확률 : {round(score, 3)}")
print(f"가장 적합한 답변은 {best_idx} : {answers[best_idx]}")

0 : 이용하시는 은행 사이트나 앱에서 지방세 납부가 가능합니다 -> 적합 확률 : 0.873
1 : 동물 등록은 거주지 구청에서 처리하셔야 합니다 -> 적합 확률 : 0.227
2 : 출입국 관련 업무는 외교부에서 담당합니다 -> 적합 확률 : 0.222
가장 적합한 답변은 0 : 이용하시는 은행 사이트나 앱에서 지방세 납부가 가능합니다

In [116]:
import random

In [117]:
# 답변의 목록들 중 확률이 높은 상위 3개 정도의 답변을 출력 
question = random.choice(df3['고객질문'].tolist())
answers = df3['상담사답변'].tolist()

In [118]:
scores = score_pairs(question, answers)

In [119]:
len(scores)

1087

In [120]:

best_idx = np.argmax(scores)
answers[best_idx]

'공공임대는 시나 국가에서 하는 분양이고 민간임대는 말 그대로 민간기업이 분양하는 것을 말합니다.'

In [121]:
question

'용산구에 있는 박물관관련 문의 드립니다.'

In [122]:
# 1일 확률이 높은 상위 3개의 위치
answers_df = pd.DataFrame(zip(answers, scores), columns = ['answer', 'score'])
answers_df.sort_values('score', ascending=False, inplace = True)
answers_df['question'] = question
answers_df.head()

,answer,score,question
429,공공임대는 시나 국가에서 하는 분양이고 민간임대는 말 그대로 민간기업이 분양하는 것...,0.899421,용산구에 있는 박물관관련 문의 드립니다.
270,성동 금호 용담 무지개 성수 청계도서관이 있습니다.,0.893306,용산구에 있는 박물관관련 문의 드립니다.
229,성동 금호 용담 무지개 성수 청계도서관이 있습니다.,0.893306,용산구에 있는 박물관관련 문의 드립니다.
979,성동 금호 용담 무지개 성수 청계도서관 있습니다.,0.887200,용산구에 있는 박물관관련 문의 드립니다.
923,성동 금호 용담 무지개 성수 청계도서관 있습니다.,0.887200,용산구에 있는 박물관관련 문의 드립니다.

In [123]:
# 오름차순 정렬의 인덱스의 값을 확인 
# argsort() : 오름차순 정렬에서 인덱스의 값을 출력 
# score에 - 기호를 사용하여 정렬
# 반대로 뒤집기 [::-1]
# np.flip() : 반대로 뒤집는 함수 
sort_idx = np.argsort(-np.array(scores))
sort_idx

array([429, 270, 229, ...,  40, 708, 395], shape=(1087,))

In [124]:
np.argsort(scores)[::-1]

array([429, 270, 229, ...,  40, 708, 395], shape=(1087,))

In [125]:
np.flip( np.argsort(scores) )

array([429, 270, 229, ...,  40, 708, 395], shape=(1087,))

In [126]:
print(f"질문 : {question}")
for idx in sort_idx[:5]:
    print(f"답변 : {answers[idx]}, 적합 확률 : {round(scores[idx], 4)}")

질문 : 용산구에 있는 박물관관련 문의 드립니다.
답변 : 공공임대는 시나 국가에서 하는 분양이고 민간임대는 말 그대로 민간기업이 분양하는 것을 말합니다., 적합 확률 : 0.8994
답변 : 성동 금호 용담 무지개 성수 청계도서관이 있습니다., 적합 확률 : 0.8933
답변 : 성동 금호 용담 무지개 성수 청계도서관이 있습니다., 적합 확률 : 0.8933
답변 : 성동 금호 용담 무지개 성수 청계도서관 있습니다., 적합 확률 : 0.8872
답변 : 성동 금호 용담 무지개 성수 청계도서관 있습니다., 적합 확률 : 0.8872

In [127]:
# 파인튜닝이 된 모델을 로드 
model2 = BertForSequenceClassification.from_pretrained("./model2")

OSError: Error no file named model.safetensors, or pytorch_model.bin, found in directory ./model2.