In [1]:
import requests 
from bs4 import BeautifulSoup as bs
import pandas as pd

In [4]:
# 네이버 쇼핑 주소를 이용하여 requests.get() html 문서를 받아온다. 
res = requests.get('http://search.shopping.naver.com/search/all?where=all&frm=NVSCTAB&query=%EC%95%84%EC%9D%B4%ED%8F%B0')

# bs 타입 변경 
soup = bs(res.text, 'html.parser')

In [ ]:
soup

In [6]:
# webdriver -> 웹 브라우져을 제어
from selenium import webdriver
# By -> element(Tag) 접근하기 위한 기능
from selenium.webdriver.common.by import By
# Keys -> 키보드의 이벤트들
from selenium.webdriver.common.keys import Keys

In [14]:
# 웹 브라우져를 실행 -> 웹브라우져를 제어(변수에 저장)
driver = webdriver.Chrome()

In [15]:
# 웹 브라우져에 주소를 입력 
driver.get('http://www.naver.com')

#### seleniumd안에 webdriver에서 Tag를 찾는 내장 함수 
- find_element()
    - 특정 조건에 맞은 태그 중 첫번째 태그를 선택
    - bs에서 find() 흡사한 기능
- find_elements()
    - 특정 조건에 맞는 태그 모두를 추출
    - bs에서 find_all() 흡사한 기능 
    - tag들이 모인 list형태라 생각하시면 됨

In [16]:
# 네이버 메인 화면에서 검색어를 입력하는 input Tag는 id 가 query 이다. 
search_element = driver.find_element(By.ID, 'query')

In [17]:
# search_element -> 검색어 입력창
# 입력할 데이터를 보내준다. python에서 webdriver로 보낸다. 
search_element.send_keys('아이폰')

In [18]:
# 검색어의 입력이 끝났으면 ENTER키를 눌러서 검색을 시작 
# 키보드 이벤트 중 ENTER 이벤트 발생
search_element.send_keys(Keys.ENTER)

In [20]:
# 하이퍼링크 의 콘텐츠 데이터가 '쇼핑'인 태그를 선택 
len(driver.find_elements(By.LINK_TEXT, '쇼핑'))

1

In [21]:
shopping_button = driver.find_element(By.LINK_TEXT, '쇼핑')

In [22]:
# 쇼핑 버튼을 클릭한다. 
shopping_button.click()

In [24]:
# 웹 브라우져(driver)에 있는 HTML 문서를 python으로 가져온다. 
html_data = driver.page_source

In [26]:
soup = bs(html_data, 'html.parser')

In [28]:
soup.title

In [29]:
# driver에 탭이 2개가 생기는 경우 
# 일반적으로  driver.page_source를 가져오면 1번 탭의 정보를 제공
# 탭의 정보(주소)를 가져온다 

driver.window_handles

['D51E376912D786DB47228779792B191A', 'D1B9E56B5A140B63C8D2D34C479A3CF0']

In [30]:
# driver에서 탭을 이동 : 창을 변경 swich_to.whindow(탭의 정보)
driver.switch_to.window(
    driver.window_handles[1]
)

In [31]:
html_data = driver.page_source
soup = bs(html_data, 'html.parser')

In [32]:
soup.title

In [33]:
# 상품의 정보가 모두 들어는 영역인 div태그 중 id가 content 태그를 추출
items_div = soup.find(
    'div',
    attrs = {
        'id' : 'content'
    }
)

In [34]:
items_div

<div class="style_content_wrap__Qi3cI" id="content"><div class="style_content__AlF53"><div class="seller_filter_area"><h3 class="blind">판매처</h3><ul class="subFilter_seller_filter__qfsMY"><li class="active _nlog_click _nlog_impression_element" data-shp-area="flt_cor.tab" data-shp-area-id="tab" data-shp-area-type="slot" data-shp-contents-dtl='[{"key":"filter_value_id","value":"total"}]' data-shp-contents-grp="filter" data-shp-contents-id="전체" data-shp-contents-rank="1" data-shp-contents-type="PC 탭" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185"><a class="subFilter_filter__KS6xJ" href="#" role="button">전체<span class="subFilter_num__effPz">4,920,019</span><span class="blind">선택됨</span></a></li><li class="_nlog_click _nlog_impression_element" data-shp-area="flt_cor.tab" data-shp-area-id="tab" data-shp-area-type="slot" data-shp-contents-dtl='[{"key":"filter_value_id","value":"model"}]' data-shp-contents-grp="filter" data-shp-contents-id="가격비교" data-shp-contents-rank="2" data-shp-contents-type="PC 탭" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185"><a class="subFilter_filter__KS6xJ" href="#" role="button">가격비교</a></li><li class="_nlog_click _nlog_impression_element" data-shp-area="flt_cor.tab" data-shp-area-id="tab" data-shp-area-type="slot" data-shp-contents-dtl='[{"key":"filter_value_id","value":"checkout"}]' data-shp-contents-grp="filter" data-shp-contents-id="네이버페이" data-shp-contents-rank="3" data-shp-contents-type="PC 탭" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185"><a class="subFilter_filter__KS6xJ" href="#" role="button">네이버페이</a></li><li class="_nlog_click _nlog_impression_element" data-shp-area="flt_cor.tab" data-shp-area-id="tab" data-shp-area-type="slot" data-shp-contents-dtl='[{"key":"filter_value_id","value":"department"}]' data-shp-contents-grp="filter" data-shp-contents-id="백화점/홈쇼핑" data-shp-contents-rank="4" data-shp-contents-type="PC 탭" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185"><a class="subFilter_filter__KS6xJ" href="#" role="button">백화점/홈쇼핑</a></li><li class="_nlog_click _nlog_impression_element" data-shp-area="flt_cor.tab" data-shp-area-id="tab" data-shp-area-type="slot" data-shp-contents-dtl='[{"key":"filter_value_id","value":"window"}]' data-shp-contents-grp="filter" data-shp-contents-id="쇼핑윈도" data-shp-contents-rank="5" data-shp-contents-type="PC 탭" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185"><a class="subFilter_filter__KS6xJ" href="#" role="button">쇼핑윈도</a></li><li class="_nlog_click _nlog_impression_element" data-shp-area="flt_cor.tab" data-shp-area-id="tab" data-shp-area-type="slot" data-shp-contents-dtl='[{"key":"filter_value_id","value":"overseas"}]' data-shp-contents-grp="filter" data-shp-contents-id="해외직구" data-shp-contents-rank="6" data-shp-contents-type="PC 탭" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185"><a class="subFilter_filter__KS6xJ" href="#" role="button">해외직구</a></li></ul><div class="subFilter_sort_area__h0sxH"><div class="subFilter_sort_box__js3FA"><span class="blind">정렬</span><a class="subFilter_sort__4Q_hv subFilter_is_active__k0gek _nlog_click _nlog_impression_element" data-shp-area="flt_cor.sort" data-shp-area-id="sort" data-shp-area-type="slot" data-shp-contents-grp="filter" data-shp-contents-id="네이버 랭킹순" data-shp-contents-type="정렬옵션" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">네이버 랭킹순<span class="blind">선택</span></a><div class="subFilter_layer_ranking__QSyoY"><div class="layer_content"><strong class="subFilter_title__nZDDn">네이버 가격비교 랭킹순</strong><p class="subFilter_text__2Tq4R">적합도 지수, 상품의 인기도/신뢰도 지수 등을 점수화하여 정렬<br/>단, 광고상품은 별도기준에 따라 상단정렬</p><ul class="subFilter_desc__e5zj6"><li><em>적합도 지수</em> : 검색어에 대한 상품 정보 연관도/카테고리 선호도</li><li><em>인기도 지수</em> : 네이버 가격비교를 통한 상품클릭수, 판매실적, 구매평수, 최신성</li><li><em>신뢰도 지수</em> : 네이버 가격비교 페널티, 상품명 SEO 스코어</li></ul></div></div><a class="subFilter_sort__4Q_hv _nlog_click _nlog_impression_element" data-shp-area="flt_cor.sort" data-shp-area-id="sort" data-shp-area-type="slot" data-shp-contents-grp="filter" data-shp-contents-id="낮은 가격순" data-shp-contents-type="정렬옵션" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">낮은 가격순</a><a class="subFilter_sort__4Q_hv _nlog_click _nlog_impression_element" data-shp-area="flt_cor.sort" data-shp-area-id="sort" data-shp-area-type="slot" data-shp-contents-grp="filter" data-shp-contents-id="높은 가격순" data-shp-contents-type="정렬옵션" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">높은 가격순</a><a class="subFilter_sort__4Q_hv _nlog_click _nlog_impression_element" data-shp-area="flt_cor.sort" data-shp-area-id="sort" data-shp-area-type="slot" data-shp-contents-grp="filter" data-shp-contents-id="리뷰 많은순" data-shp-contents-type="정렬옵션" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">리뷰 많은순</a><a class="subFilter_sort__4Q_hv _nlog_click _nlog_impression_element" data-shp-area="flt_cor.sort" data-shp-area-id="sort" data-shp-area-type="slot" data-shp-contents-grp="filter" data-shp-contents-id="리뷰 좋은순" data-shp-contents-type="정렬옵션" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">리뷰 좋은순</a><div class="subFilter_layer_ranking__QSyoY subFilter_review__tkvw_"><div class="layer_content"><strong class="subFilter_title__nZDDn">리뷰 좋은순</strong><p class="subFilter_text__2Tq4R">리뷰 관련 상품 인기도 지수, 키워드 및 카테고리 유사도를 점수화하여 정렬</p></div></div><a class="subFilter_sort__4Q_hv _nlog_click _nlog_impression_element" data-shp-area="flt_cor.sort" data-shp-area-id="sort" data-shp-area-type="slot" data-shp-contents-grp="filter" data-shp-contents-id="등록일순" data-shp-contents-type="정렬옵션" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">등록일순</a></div><div class="subFilter_sort_choice__ZT2VI"><div class="subFilter_mall_choice__QF432"><a class="subFilter_btn_mall__B2_Dg _nlog_click" data-shp-area="flt_cor.shoptype" data-shp-area-id="shoptype" data-shp-area-type="action" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">쇼핑몰선택</a><div class="subFilter_layer_mall__5wVLA"><ul class="subFilter_sort_tab__N1GYa"><li class="active _nlog_click _nlog_impression_element" data-shp-area="flt_cor.shoptab" data-shp-area-id="shoptab" data-shp-area-type="slot" data-shp-contents-grp="filter" data-shp-contents-id="" data-shp-contents-rank="1" data-shp-contents-type="오픈마켓/종합몰" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185"><a class="subFilter_tab__Qjmqm" href="#" role="button">오픈마켓/종합몰<span class="blind">선택</span></a></li><li class="_nlog_click _nlog_impression_element" data-shp-area="flt_cor.shoptab" data-shp-area-id="shoptab" data-shp-area-type="slot" data-shp-contents-grp="filter" data-shp-contents-id="" data-shp-contents-rank="2" data-shp-contents-type="백화점/홈쇼핑" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185"><a class="subFilter_tab__Qjmqm" href="#" role="button">백화점/홈쇼핑</a></li><li class="_nlog_click _nlog_impression_element" data-shp-area="flt_cor.shoptab" data-shp-area-id="shoptab" data-shp-area-type="slot" data-shp-contents-grp="filter" data-shp-contents-id="" data-shp-contents-rank="3" data-shp-contents-type="면세점" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185"><a class="subFilter_tab__Qjmqm" href="#" role="button">면세점</a></li><li class="_nlog_click _nlog_impression_element" data-shp-area="flt_cor.shoptab" data-shp-area-id="shoptab" data-shp-area-type="slot" data-shp-contents-grp="filter" data-shp-contents-id="" data-shp-contents-rank="4" data-shp-contents-type="해외쇼핑" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185"><a class="subFilter_tab__Qjmqm" href="#" role="button">해외쇼핑</a></li><li class="_nlog_click _nlog_impression_element" data-shp-area="flt_cor.shoptab" data-shp-area-id="shoptab" data-shp-area-type="slot" data-shp-contents-grp="filter" data-shp-contents-id="" data-shp-contents-rank="5" data-shp-contents-type="마트/소셜" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185"><a class="subFilter_tab__Qjmqm" href="#" role="button">마트/소셜</a></li><li class="_nlog_click _nlog_impression_element" data-shp-area="flt_cor.shoptab" data-shp-area-id="shoptab" data-shp-area-type="slot" data-shp-contents-grp="filter" data-shp-contents-id="" data-shp-contents-rank="6" data-shp-contents-type="여행/티켓" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185"><a class="subFilter_tab__Qjmqm" href="#" role="button">여행/티켓</a></li><li class="_nlog_click _nlog_impression_element" data-shp-area="flt_cor.shoptab" data-shp-area-id="shoptab" data-shp-area-type="slot" data-shp-contents-grp="filter" data-shp-contents-id="" data-shp-contents-rank="7" data-shp-contents-type="소호" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185"><a class="subFilter_tab__Qjmqm" href="#" role="button">소호</a></li></ul><div class="subFilter_list_sort__1h4oN"><span class="blind">정렬</span><a class="subFilter_sort__4Q_hv active _nlog_click _nlog_impression_element" data-shp-area="flt_cor.shopsort" data-shp-area-id="shopsort" data-shp-area-type="slot" data-shp-contents-grp="filter" data-shp-contents-id="상품수순" data-shp-contents-type="오픈마켓/종합몰" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">상품수순</a><a class="subFilter_sort__4Q_hv _nlog_click _nlog_impression_element" data-shp-area="flt_cor.shopsort" data-shp-area-id="shopsort" data-shp-area-type="slot" data-shp-contents-grp="filter" data-shp-contents-id="가나다순" data-shp-contents-type="오픈마켓/종합몰" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">가나다순</a>.</div><div class="subFilter_list_mall_scroll__pkXmi"></div><div class="subFilter_btn_box__Kk1AD"><a class="subFilter_btn_confirm__L_2tx _nlog_impression_element" data-shp-area="flt_cor.shoptypesave" data-shp-area-id="shoptypesave" data-shp-area-type="slot" data-shp-contents-grp="filter" data-shp-contents-id="" data-shp-contents-type="오픈마켓/종합몰" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">저장</a><a class="subFilter_btn_cancel__ORpvr _nlog_click" data-shp-area="flt_cor.shoptypeclose" data-shp-area-id="shoptypeclose" data-shp-area-type="action" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">취소</a></div><a class="subFilter_btn_close__6YJa8 _nlog_click" data-shp-area="flt_cor.shoptypeclose" data-shp-area-id="shoptypeclose" data-shp-area-type="action" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">닫기</a></div></div><div class="subFilter_select_box__X85_8"><a class="subFilter_btn_select__Cl27D _nlog_click _nlog_impression_element" data-shp-area="flt_cor.pdtype" data-shp-area-id="pdtype" data-shp-area-type="slot" data-shp-contents-grp="filter" data-shp-contents-id="" data-shp-contents-type="상품타입" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">상품타입(전체)</a><ul class="subFilter_layer_list__RLoFF"><li><a class="subFilter_select__LwxTx _nlog_click _nlog_impression_element" data-shp-area="flt_cor.pdtype" data-shp-area-id="pdtype" data-shp-area-type="slot" data-shp-contents-grp="filter" data-shp-contents-id="상품타입(전체)" data-shp-contents-type="상품타입" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">상품타입(전체)</a></li><li class=""><a class="subFilter_select__LwxTx _nlog_click _nlog_impression_element" data-shp-area="flt_cor.pdtype" data-shp-area-id="pdtype" data-shp-area-type="slot" data-shp-contents-dtl='[{"key":"filter_value_id","value":"agency"}]' data-shp-contents-grp="filter" data-shp-contents-id="해외직구보기" data-shp-contents-rank="1" data-shp-contents-type="상품타입" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">해외직구보기</a></li><li class=""><a class="subFilter_select__LwxTx _nlog_click _nlog_impression_element" data-shp-area="flt_cor.pdtype" data-shp-area-id="pdtype" data-shp-area-type="slot" data-shp-contents-dtl='[{"key":"filter_value_id","value":"exagency"}]' data-shp-contents-grp="filter" data-shp-contents-id="해외직구제외" data-shp-contents-rank="2" data-shp-contents-type="상품타입" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">해외직구제외</a></li><li class=""><a class="subFilter_select__LwxTx _nlog_click _nlog_impression_element" data-shp-area="flt_cor.pdtype" data-shp-area-id="pdtype" data-shp-area-type="slot" data-shp-contents-dtl='[{"key":"filter_value_id","value":"used"}]' data-shp-contents-grp="filter" data-shp-contents-id="중고보기" data-shp-contents-rank="3" data-shp-contents-type="상품타입" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">중고보기</a></li><li class=""><a class="subFilter_select__LwxTx _nlog_click _nlog_impression_element" data-shp-area="flt_cor.pdtype" data-shp-area-id="pdtype" data-shp-area-type="slot" data-shp-contents-dtl='[{"key":"filter_value_id","value":"exused"}]' data-shp-contents-grp="filter" data-shp-contents-id="중고제외" data-shp-contents-rank="4" data-shp-contents-type="상품타입" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">중고제외</a></li><li class=""><a class="subFilter_select__LwxTx _nlog_click _nlog_impression_element" data-shp-area="flt_cor.pdtype" data-shp-area-id="pdtype" data-shp-area-type="slot" data-shp-contents-dtl='[{"key":"filter_value_id","value":"rental"}]' data-shp-contents-grp="filter" data-shp-contents-id="렌탈보기" data-shp-contents-rank="5" data-shp-contents-type="상품타입" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">렌탈보기</a></li><li class=""><a class="subFilter_select__LwxTx _nlog_click _nlog_impression_element" data-shp-area="flt_cor.pdtype" data-shp-area-id="pdtype" data-shp-area-type="slot" data-shp-contents-dtl='[{"key":"filter_value_id","value":"exrental"}]' data-shp-contents-grp="filter" data-shp-contents-id="렌탈제외" data-shp-contents-rank="6" data-shp-contents-type="상품타입" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">렌탈제외</a></li></ul></div><div class="subFilter_select_box__X85_8"><a class="subFilter_btn_select__Cl27D _nlog_click _nlog_impression_element" data-shp-area="flt_cor.display" data-shp-area-id="display" data-shp-area-type="slot" data-shp-contents-grp="filter" data-shp-contents-id="" data-shp-contents-type="상품노출 수" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">40개씩 보기</a><ul class="subFilter_layer_list__RLoFF"><li class=""><a class="subFilter_select__LwxTx _nlog_click _nlog_impression_element" data-shp-area="flt_cor.display" data-shp-area-id="display" data-shp-area-type="slot" data-shp-contents-dtl='[{"key":"filter_value_id","value":"20"}]' data-shp-contents-grp="filter" data-shp-contents-id="20개씩 보기" data-shp-contents-rank="1" data-shp-contents-type="상품노출 수" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">20개씩 보기</a></li><li class="active"><a class="subFilter_select__LwxTx _nlog_click _nlog_impression_element" data-shp-area="flt_cor.display" data-shp-area-id="display" data-shp-area-type="slot" data-shp-contents-dtl='[{"key":"filter_value_id","value":"40"}]' data-shp-contents-grp="filter" data-shp-contents-id="40개씩 보기" data-shp-contents-rank="2" data-shp-contents-type="상품노출 수" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">40개씩 보기</a></li><li class=""><a class="subFilter_select__LwxTx _nlog_click _nlog_impression_element" data-shp-area="flt_cor.display" data-shp-area-id="display" data-shp-area-type="slot" data-shp-contents-dtl='[{"key":"filter_value_id","value":"60"}]' data-shp-contents-grp="filter" data-shp-contents-id="60개씩 보기" data-shp-contents-rank="3" data-shp-contents-type="상품노출 수" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">60개씩 보기</a></li><li class=""><a class="subFilter_select__LwxTx _nlog_click _nlog_impression_element" data-shp-area="flt_cor.display" data-shp-area-id="display" data-shp-area-type="slot" data-shp-contents-dtl='[{"key":"filter_value_id","value":"80"}]' data-shp-contents-grp="filter" data-shp-contents-id="80개씩 보기" data-shp-contents-rank="4" data-shp-contents-type="상품노출 수" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button">80개씩 보기</a></li></ul></div><div class="subFilter_type_choice__ywsBT"><a class="subFilter_btn_list__58VQk active _nlog_click _nlog_impression_element" data-shp-area="flt_cor.viewtype" data-shp-area-id="viewtype" data-shp-area-type="slot" data-shp-contents-dtl='[{"key":"filter_value_id","value":"list"}]' data-shp-contents-grp="filter" data-shp-contents-id="리스트형" data-shp-contents-rank="1" data-shp-contents-type="뷰타입" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button"><span class="blind">list<!-- --> <!-- -->선택</span></a><a class="subFilter_btn_image__f1VPa _nlog_click _nlog_impression_element" data-shp-area="flt_cor.viewtype" data-shp-area-id="viewtype" data-shp-area-type="slot" data-shp-contents-dtl='[{"key":"filter_value_id","value":"image"}]' data-shp-contents-grp="filter" data-shp-contents-id="이미지형" data-shp-contents-rank="2" data-shp-contents-type="뷰타입" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button"><span class="blind">image<!-- --> </span></a><a class="btn_bigImage _nlog_click _nlog_impression_element" data-shp-area="flt_cor.viewtype" data-shp-area-id="viewtype" data-shp-area-type="slot" data-shp-contents-dtl='[{"key":"filter_value_id","value":"bigImage"}]' data-shp-contents-grp="filter" data-shp-contents-id="큰이미지형" data-shp-contents-rank="3" data-shp-contents-type="뷰타입" data-shp-inventory="flt_cor" data-shp-nsc="svc.shopping.v3" data-shp-page-key="100360185" href="#" role="button"><span class="blind">bigImage<!-- --> </span></a></div></div></div></div><div class="basicList_list_basis__XVx_G"><div><div class="adProduct_item__T7utB"><div class="adProduct_inner__xrv_c"><div class="adProduct_img_area__eubFn"><div class="thumbnail_thumb_wrap__X013_ _wrapper"><a class="thumbnail_thumb__MG0r2 linkAnchor _nlog_click _nlog_impression_element" data-shp-area="lst*A.img" data-shp-area-dtl='[{"key":"trtr","value":"pla"}]' data-shp-area-id="img" data-shp-area-type="slot" data-shp-contents-dtl='[{"key":"nv_mid","value":"56708614382"},{"key":"price","value":"1790000"},{"key":"exhibition_category","value":"자급제폰"},{"key":"nfa_type","value":"FASTDLVRY"},{"key":"ad_expose_order","value":"1"},{"key":"std_yn","value":"n"},{"key":"search_nginx_pageid","value":"jPmetdqWrIkgWssLlRV-261239"}]' data-shp-contents-grp="ad" data-shp-contents-id="nad-a001-02-000000416673505" data-shp-contents-provider-dtl='[{"key":"brandstore_type","value":"n"}]' data-shp-contents-provider-id="613264" data-shp-contents-provider-type="mall_seq" data-shp-contents-ra

In [37]:
import re

In [40]:
len(
    items_div.find_all(
        'div', 
        attrs = {
            'class' : re.compile('adProduct_item')
        }
    )
)

2

In [39]:
len(
    items_div.select(
        "div[class^='product_item']"
    )
)

3

In [ ]:
# product_item들의 상품의 이름과 가격을 추출
# 상품명 -> product_title__xxxxx
# 가격 -> price
# 배송비 -> price_delivery_fee__xxxxx
item_list = items_div.find_all(
    'div', 
    attrs = {
        'class' : re.compile('product_item')
    }
)

In [48]:
item_list[0].find(
    'span', 
    attrs = {
        'class' : 'price'
    }
).get_text()

'440,000원'

In [ ]:
# 반복문을 이용하여 item_list의 상품명, 가격, 배송비 하나의 2차원 데이터로 생성
values = []

for item in item_list:    
    # 상품명을 추출 
    item_name = item.find(
        'div', 
        attrs = {
            'class' : re.compile('product_title')
        }
    ).get_text()

    # 가격을 추출
    item_price = item.find(
        'span', 
        attrs = {
            'class' : 'price'
        }
    ).get_text()

    # 배송비 추출 
    item_fee = item.find(
        'div', 
        attrs = {
            'class' : re.compile('price_delivery_fee')
        }
    ).get_text()

    # 상품의 링크 주소를 추출 (상품명 추출해서 이 안에서 a태그 찾고 href 속성 값 추출)
    name_tag = item.find(
        'div', 
        attrs = {
            'class' : re.compile('product_title')
        }
    )
    item_url = name_tag.find('a')['href']

    # 상품명과 가격 배송비를 딕셔너리형태로 생성하여 values에 추가 
    values.append(
        {
            '상풍명' : item_name, 
            '가격' : item_price, 
            '배송비' : item_fee, 
            'url' : item_url
        }
    )
# values에 링크 주소로 포함 -> 일반적으로 a태그에 존재 -> href의 속성의 값
values

In [52]:
pd.DataFrame(values)

,상풍명,가격,배송비,url
0,애플 Apple 아이폰 16e 128GB 미개봉 새제품,"440,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=WUtSck8dx...
1,[대여] 애플 17 프로 아이폰 대여 렌탈 합정 잠실 서울역,"29,600원",배송비무료,https://cr.shopping.naver.com/adcr?x=aEl3VGTIA...
2,아이폰 17e 256GB [자급제],"최저990,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=Vs5enPU8N...

1. driver에서 스크롤을 내려준다. 
2. driver에서 html 문서를 돌려받는다. 
3. bs()를 이용하여 데이터 파싱
4. 상품명, 가격, 배송비, 주소 를 추출하여 데이터프레임으로 완성

In [53]:
# 스크롤 맨 밑으로 내린다. 
driver.execute_script(
    "window.scrollTo(0, document.body.scrollHeight)"
)

In [69]:
# driver에서 스크롤 일정 간격으로 내려준다. 
driver.execute_script(
    "window.scrollBy(0, 1000)"
)

In [72]:
# driver에서 html 문서를 불러온다. 
html_data = driver.page_source
# bs() 타입 변경
soup = bs(html_data, 'html.parser')

In [75]:
# 상품명, 가격, 배송비, 주소를 추출
items_div = soup.find(
    'div', 
    attrs = {
        'id' : 'content'
    }
)
item_list = items_div.find_all(
    'div', 
    attrs = {
        'class' : re.compile('product_item')
    }
)
len(item_list)

40

In [ ]:
values = []

for item in item_list:    
    # 상품명을 추출 
    item_name = item.find('div', 
        attrs = {'class' : re.compile('product_title')}
    ).get_text()

    # 가격을 추출
    item_price = item.find('span', 
        attrs = {'class' : 'price'}
    ).get_text()

    # 배송비 추출 
    item_fee = item.find('div', 
        attrs = {'class' : re.compile('price_delivery_fee')}
    ).get_text()

    # 상품의 링크 주소를 추출 (상품명 추출해서 이 안에서 a태그 찾고 href 속성 값 추출)
    name_tag = item.find('div', 
            attrs = {'class' : re.compile('product_title')}
    )
    item_url = name_tag.find('a')['href']

    # 상품명과 가격 배송비를 딕셔너리형태로 생성하여 values에 추가 
    values.append(
        {
            '상풍명' : item_name, 
            '가격' : item_price, 
            '배송비' : item_fee, 
            'url' : item_url
        }
    )

In [82]:
# 데이터프레임 
df = pd.DataFrame(values)
df

,상풍명,가격,배송비,url
0,애플 Apple 아이폰 16e 128GB 미개봉 새제품,"440,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=WUtSck8dx...
1,[대여] 애플 17 프로 아이폰 대여 렌탈 합정 잠실 서울역,"29,600원",배송비무료,https://cr.shopping.naver.com/adcr?x=aEl3VGTIA...
2,아이폰 17e 256GB [자급제],"최저990,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=Vs5enPU8N...
3,아이폰 17 512GB [자급제],"최저1,526,400원",배송비무료,https://cr.shopping.naver.com/adcr?x=y1uWiK5Zg...
4,Apple 정품 아이폰 16 자급제,"1,150,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=qiCzpb9pA...
5,아이폰 17 프로 256GB [자급제],"최저1,790,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=gd9%2Bj0i...
6,SK 기기변경 애플 아이폰17프로 512G / iphone17 Pro,"1,440,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=RDZ%2FwEV...
7,아이폰 17 256GB [자급제],"최저1,237,980원",배송비무료,https://cr.shopping.naver.com/adcr?x=hPGGVhEAU...
8,Apple 아이폰 17 프로 자급제 256GB - 실버 MG8G4KH/A,"1,790,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=1VNj9tsxU...
9,Apple 아이폰17프로맥스 512GB Apple 미개봉 새상품,"1,160,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=tJcS%2BJt...
10,해외아이폰5C 풀박스 공기계 무음 카메라 8GB 5C,"79,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=P10GXxLL2...
11,아이폰 17 256GB Apple 미개봉 새상품,"490,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=ATgMqgwki...
12,Apple 아이폰 16프로 512GB Apple 미개봉 새상품,"890,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=Jqn8rcS%2...
13,Apple 아이폰 15프로맥스 256GB Apple 미개봉 새상품,"690,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=PLvv6uZmA...
14,Apple 아이폰17프로맥스 256GB Apple 미개봉 새상품,"1,000,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=i1bNwi8R7...
15,아이폰17 에어 256GB 미개봉 새상품,"745,930원",배송비무료,https://cr.shopping.naver.com/adcr?x=1jWUlRfMQ...
16,애플 아이폰 16e 256GB 미개봉 새상품,"583,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=cfGwyVuGI...
17,Apple 아이폰 16프로 256GB Apple 미개봉 새상품,"690,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=ziXuQ3NiN...
18,아이폰 17프로 512GB Apple 미개봉 새상품,"1,108,380원",배송비무료,https://cr.shopping.naver.com/adcr?x=A6w4McCzG...
19,[대여] 아이폰17 프로 대여 1일 단기 렌탈,"19,800원","배송비3,000원",https://cr.shopping.naver.com/adcr?x=syV%2FuV9...
20,Apple 아이폰17 프로맥스 자급제 모아보기 색상/용량 선택,"1,990,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=QzbQUJewi...
21,Apple 정품 아이폰 15 자급제,"960,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=sM5wmWBl8...
22,Apple 아이폰 16e 자급제,"769,900원",배송비무료,https://cr.shopping.naver.com/adcr?x=wKxuMfWVi...
23,해외애플 아이폰17 홍콩판 물리심+e심 무음 자급제 공기계 홍콩폰 256GB,"1,394,500원",배송비무료,https://cr.shopping.naver.com/adcr?x=vPw5D0wEW...
24,애플 아이폰 16 프로 맥스 256GB 새제품 미개봉,"1,280,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=g8Q8SbKpw...
25,아이폰 16프로 256GB Apple 미개봉 새상품,"814,090원",배송비무료,https://cr.shopping.naver.com/adcr?x=8LuXsPzo7...
26,아이폰 16프로 티타늄 256GB 미개봉 새제품,"944,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=Bu1eXhdQZ...
27,아이폰 17 프로 맥스 256GB [자급제],"최저1,990,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=hR3h8Bo%2...
28,해외아이폰 17 프로 iPhone17 Pro 홍콩판 듀얼심 무음카메라 자급제 256GB,"1,897,000원","배송비100,000원",https://cr.shopping.naver.com/adcr?x=5For6XzS1...
29,Apple 아이폰 12 mini 자급제 화이트 64GB,"348,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=F9yt63bmT...
30,해외아이폰se 아이폰se1 공기계 모두의애플 se1 골드 WIFI 16GB,"116,500원","배송비16,500원",https://cr.shopping.naver.com/adcr?x=duTVE%2Bm...
31,Apple 애플 아이폰 14 128GB 미개봉 새제품,"587,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=KBFcE0Guo...
32,애플 아이폰16E 128G / iphone-16 E / SE4,"530,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=mINcRMWoo...
33,해외아이폰SE1 올인원 풀박스 공기계 세컨폰 스페이스그레이 16GB 베이직,"86,000원","배송비9,000원",https://cr.shopping.naver.com/adcr?x=aRmKNfqom...
34,아이폰 15 128GB Apple 미개봉 새상품,"643,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=0MUrg4FYR...
35,아이폰 에어 256GB [자급제],"최저1,431,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=n5r4Fo%2B...
36,Apple 아이폰 17 Pro 자급제,"1,790,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=u9EXz26eR...
37,Apple 정품 아이폰 15 자급제,"1,090,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=9YRdBFw%2...
38,Apple 정품 아이폰 15 Pro 자급제 화이트티타늄 256GB,"1,248,000원",배송비무료,https://cr.shopping.naver.com/adcr?x=hIrnMArMl...
39,Apple 아이폰 13 미니 256GB,"239,250원",배송비무료,https://cr.shopping.naver.com/adcr?x=tyM6OdCZS...

In [78]:
# csv 파일 저장 
df.to_csv('아이폰.csv', index=False)

In [79]:
# 웹 브라우져를 종료
driver.quit()

- 수집한 데이터를 mysql db server에 저장 
    - db.py module를 이용하여 데이터를 저장 
        - table 생성 
        - insert문을 이용하여 데이터를 하나씩 대입 
        - commit() 함수를 이용해서 동기화
        - DB server와의 연결을 종료

    - pandas에 to_sql() 함수를 이용해서 데이터 저장
        - DB server의 연결 주소를 생성 (sqlalchemy 라이브러리)
        - 데이터프레임의 데이터들은 DB server로 대입

In [80]:
# db.py 로드 
from db import MyDB

In [81]:
# 클래스 생성 -> DB 정보를 가진 클래스 
db = MyDB()

In [86]:
# 데이터가 저장될 table 생성 
# 상품명(varchar(64)), 가격(varchar(32)), 배송비(varchar(32)), url(text)
table_query = """
    CREATE TABLE IF NOT EXISTS `naver_shopping`(
        `No` int PRIMARY KEY AUTO_INCREMENT, 
        `name` VARCHAR(64), 
        `price` VARCHAR(32), 
        `delivery_fee` VARCHAR(32), 
        `url` TEXT
    )
"""

In [88]:
db.sql_query(
    table_query
)

접속된 서버가 존재함

'Query OK!'

In [97]:
df.to_dict('tight')['data'][0]

['애플 Apple 아이폰 16e 128GB 미개봉 새제품',
 '440,000원',
 '배송비무료',
 'https://cr.shopping.naver.com/adcr?x=WUtSck8dxAsopM9tXkTwU%2F%2F%2F%2Fw%3D%3DspojuisFSDuU5qGAdRm2zuyxZcvrUPzk97ASbS4kXSCByoYErd7Wx1dfdVO6hh7qVt48n84dncDMDszuSszHxrcKdlAuo4CRofAy%2FiHp8jqv8RtWXQ%2B4yWv%2FzzZujOpojmqs6VA1Ip9%2BaWCyaARjJQGsvQcVfIbwfdcQu8Df56jKCsr8yynXy1Rxgr6zJJ7GpyaxxRm4H8HcYDi0B3B3iQmfQT7uWwvxdz8nMvhXCKF36a1IbrOU94c1aiygYUf%2BvpuyF5V%2BRfeSk2AMSykYXvAeL8mDjug0MMBKQwp4NOEHBz7%2BORHa%2BX777%2F5U82WuFRDpykpOqWZgZqWcBmVwRDaOol1WSMMKpom7eXpcVXYthivBWooHLkHLGxNS5B7OfcRNvmkCkGTEGnQxjgQGSKvzMybi7RS0Fk%2FkZZEnWyH%2B4ikYh%2B1eAo3s9pIcgX6%2FVYIgXIvo1wIoW71vTCRWZ4bQMix%2BJK3SiRs9wofjr0VjMTvqUaZ6cAoko%2BW901jfVf6oNYw9aUvnwg%2BxOScjoEQf%2B8ArsfZxdI%2FVW%2F55BNVWlkX647Zdjjw9%2Br5Mcvp%2Ba4%2BuqL5a1oGaC4MNiTctWmjzUaLji1QUfW5FQpucBI9A4uaHtiksl4nvd3RhSAqxa4En7Khr8n7ppXjNuEqUq7yLynv3Krj06cn3Iwvth0N9Xc50eBITwugSNPH3Ok09sVpGw61BSdoQRvEGgfFlc5w%3D%3D&nvMid=89877627274&catId=50001519']

In [98]:
list(df.values[0])

['애플 Apple 아이폰 16e 128GB 미개봉 새제품',
 '440,000원',
 '배송비무료',
 'https://cr.shopping.naver.com/adcr?x=WUtSck8dxAsopM9tXkTwU%2F%2F%2F%2Fw%3D%3DspojuisFSDuU5qGAdRm2zuyxZcvrUPzk97ASbS4kXSCByoYErd7Wx1dfdVO6hh7qVt48n84dncDMDszuSszHxrcKdlAuo4CRofAy%2FiHp8jqv8RtWXQ%2B4yWv%2FzzZujOpojmqs6VA1Ip9%2BaWCyaARjJQGsvQcVfIbwfdcQu8Df56jKCsr8yynXy1Rxgr6zJJ7GpyaxxRm4H8HcYDi0B3B3iQmfQT7uWwvxdz8nMvhXCKF36a1IbrOU94c1aiygYUf%2BvpuyF5V%2BRfeSk2AMSykYXvAeL8mDjug0MMBKQwp4NOEHBz7%2BORHa%2BX777%2F5U82WuFRDpykpOqWZgZqWcBmVwRDaOol1WSMMKpom7eXpcVXYthivBWooHLkHLGxNS5B7OfcRNvmkCkGTEGnQxjgQGSKvzMybi7RS0Fk%2FkZZEnWyH%2B4ikYh%2B1eAo3s9pIcgX6%2FVYIgXIvo1wIoW71vTCRWZ4bQMix%2BJK3SiRs9wofjr0VjMTvqUaZ6cAoko%2BW901jfVf6oNYw9aUvnwg%2BxOScjoEQf%2B8ArsfZxdI%2FVW%2F55BNVWlkX647Zdjjw9%2Br5Mcvp%2Ba4%2BuqL5a1oGaC4MNiTctWmjzUaLji1QUfW5FQpucBI9A4uaHtiksl4nvd3RhSAqxa4En7Khr8n7ppXjNuEqUq7yLynv3Krj06cn3Iwvth0N9Xc50eBITwugSNPH3Ok09sVpGw61BSdoQRvEGgfFlc5w%3D%3D&nvMid=89877627274&catId=50001519']

In [ ]:
# insert 문을 생성 
# 첫번째 컬럼이 No -> auto_increment 기능을 사용 -> 데이터를 넣을 필요가 없음 
insert_query = """
    INSERT INTO `naver_shopping`(
        `name`, `price`, `delivery_fee`, `url`
    )
    VALUES (%s, %s, %s, %s)
"""
# 반복문을 이용해서 데이터프레임의 데이터들을 하나씩 insert 작업 
# len(df)
for i in range(len(df)):
    # i -> 위치 0부터 39까지 
    value = list(df.values[i])
    # print(value)
    # break
    # MyDB 안에 sql_query에 2번째 인자값인 datas 가변인자 허용 -> list 형태를 그대로 입력 x
    # db.sql_query(insert_query, value[0], value[1], value[2], value[3])
    db.sql_query(insert_query, *value)

In [102]:
# DB server 동기화
db.commit()

In [ ]:
# sqlalchemy 라이브러리 설치 
# !pip install sqlalchemy

In [104]:
from sqlalchemy import create_engine

In [105]:
# create_engine을 이용해서 서버의 정보를 입력 
# sql서버의 주소 : mysql+pymysql://유저명:비밀번호@DB서버의주소:포트번호/데이터베이스명
engine = create_engine(
    "mysql+pymysql://root:1234@localhost:3306/multicam"
)

In [108]:
# DataFrame에 to_sql() 함수를 이용
    # name : 테이블의 이름  (필수)
    # con : 데이터베이스의 주소(engine)  (필수)
    # index : 인덱스 저장 여부 (기본값 : True)
    # if_exists : 
        # replace(교체) -> 기존의 데이터는 제거, 새로운 데이터 대입
        # fail(실패 처리, 기본값) -> 기존의 테이블이 존재하면 에러 발생
        # append(추가) -> 기존의 데이터 밑에 데이터를 추가하는 방식
df.to_sql(name = "naver", con = engine, index=False, if_exists='append')

40

In [ ]:
engine2 = create_engine(
    "mysql+pymysql://test_user:1234@localhost:3306/multicam"
)

In [110]:
# 테이블 이름은 각자의 이름으로 to_sql() 실행 
df.to_sql(name='문병선', con=engine2, index=False)

40