In [1]:
from glob import glob 
import pandas as pd

In [2]:
file_list = glob("../data/인터뷰/*.json")

In [3]:
df = pd.read_json(file_list[0])

In [4]:
df

,version,dataSet,rawDataInfo
info,1.0,"{'date': '20230116', 'occupation': 'BM', 'chan...",NaN
question,1.0,{'raw': {'text': '지원자님께서 가지고 계신 나만의 스트레스 해소법이 ...,"{'fileFormat': 'wav', 'fileSize': 664398, 'dur..."
answer,1.0,{'raw': {'text': '저는 저 혼자 시간을 보내는 것을 우선적으로 하고요...,"{'fileFormat': 'wav', 'fileSize': 1900238, 'du..."

In [5]:
import json

In [6]:
with open(file_list[0], 'r', encoding='utf-8') as f :
    data = json.load(f)

In [ ]:
f2 = open(file_list[1], 'r', encoding='utf-8')
data2 = json.load(f2)

In [8]:
from pprint import pprint

In [12]:
pprint(data['dataSet']['answer']['summary']['text'])

('저는 혼자 시간을 보내는 것을 우선적으로 하며, 혼자 산책을 하거나 혼자 카페를 간다든지 또는 혼자 노래방을 간다든지 해서 스트레스를 '
 '해소하는 편입니다. 혼자의 시간이 있으면 생각 정리도 되고 제 안에 있던 응어리도 저절로 풀러지는 것을 경험하게 되었습니다.')

In [13]:
answers, summarys = [] , []

for file in file_list:
    try:
        with open(file, 'r', encoding='utf-8') as f:
            dict_data = json.load(f)
            answer = dict_data['dataSet']['answer']['raw']['text']
            summary = dict_data['dataSet']['answer']['summary']['text']
            answers.append(answer)
            summarys.append(summary)
    except Exception as e:
        print(e)

Invalid control character at: line 23 column 135 (char 755)
Invalid control character at: line 23 column 571 (char 1132)
Invalid control character at: line 23 column 433 (char 1029)

In [15]:
len(summarys)

12801

In [16]:
df = pd.DataFrame(zip(answers, summarys), columns = ['answer', 'summary'])
df.head()

,answer,summary
0,저는 저 혼자 시간을 보내는 것을 우선적으로 하고요. 예를 들어서 혼자 산책을 한다...,"저는 혼자 시간을 보내는 것을 우선적으로 하며, 혼자 산책을 하거나 혼자 카페를 간..."
1,네 여러 관계자와 협력을 해서 네 성공적으로 일정을 수행해 본 적이 있었고요. 아무...,여러 관계자와 협력을 해서 성공적으로 일정을 수행해 본 적이 있습니다. 각자 보이는...
2,대부분은 왠지 전사나 마법사를 고를 것 같은데요. 저는 조금은 독특하게 힐러 역할을...,"대부분 전사나 마법사를 고를 것 같은데, 저는 힐러 역할을 해보고 싶습니다. 힐러는..."
3,네 소통 능력을 키우기 위해서는 저는 일단 말을 많이 해야 된다 라고 생각을 하는데...,"소통 능력을 키우기 위해서는 말을 많이 해야 되는데, 동아리 가입이나 어떤 커뮤니티..."
4,네 과거에 프로젝트를 수행했던 경험이 있구요. 저는 리더보다는 주변 사람들을 챙기고...,저는 리더보다는 주변 사람들을 챙기고 그들의 의견을 듣는 중재자 역할을 했습니다. ...

In [17]:
df.to_csv("인터뷰.csv", index=False)

### 복습 
- answers, summarys데이터에서 상위의 100개의 데이터를 train 사용 
- 하위의 20개의 데이터를 validation으로 사용 
- DatasetDict를 생성 
- 모델은 'digit82/kobart-summarization' 사용
- tokenizer를 이용 해서 토큰화 인코딩 
- kobart 모델 trainer을 이용하여 반복 학습 
    - input의 최대 사이즈 : 512
    - output의 최대 사이즈 : 256